### ISSUE TITLE
[Bug] Torch light only affects block hanging/standing on when unloading and reloading the chunk.

### ISSUE THREAD

**Issue by mibby** [NavidK0/Carbon#10]
See comments here.
https://github.com/NavidK0/Carbon/commit/8d241f20f1ed6a37b8d47d14529e41b5c0e96130

**Comment by Shevchik** [comment]
Should be fixed. Somebody used wrong name for unlit redstone torch. Or maybe it's the new injection method fixed it.

**Comment by mibby** [comment]
Great, I'll recompile and double check. :) ~~Do you want to reinject torches now?~~
https://github.com/NavidK0/Carbon/commit/c6b8381d4dbb053d2121378d947b1768c93b90ca

Edit: Nevermind. I see they are re-injected.

**Comment by Shevchik** [comment]
Heh, looks like it stopped working for some reason again >_<

**Comment by mibby** [comment]
Ah, darn. I shall wait then.

**Comment by Shevchik** [comment]
Looks like i nailed it. Still don't know why it is like that.

**Comment by mibby** [comment]
Great, I'll double check to verify it is fixed.

**Comment by Shevchik** [comment]
So i found it, i's the method a(float) int Block which controls block light level.
Should be able to apply light level to sea lantern now.

**Comment by mibby** [comment]
~~And that would fix torches properly? Or would it be used to introduce light levels into sea lanterns?~~

Notice the edit. Sounds great! Looking forward to sea lantern fix.

**Comment by Shevchik** [comment]
Already

**Comment by mibby** [comment]
Haha, thanks. You're fast. :P Updating again to verify. Will close tickets once verified.

**Comment by mibby** [comment]
Torches confirmed fixed per this commit.
https://github.com/NavidK0/Carbon/commit/7113dd0e4127206f3dff7c83b141f62b509028cc

Old torches need to be placed again to update the block light levels, but new torches are correctly saving when unloading the chunk and reloading it.
