### ISSUE TITLE
1.8 MobSpawners 

### ISSUE THREAD

**Issue by unicxa** [NavidK0/Carbon#101]
I don't know if this has been added because I have been on a camping trip and I have poor service coverage up here, but I was wondering if you can call 1.8 spawners to spawn 1.8 entitys I.E Endermites, Guardians, rabbits if this issue is open I will be glad to work on it as soon as I get home I'm heading back to my home today but I'm mainly asking has this feature been added
:-)

**Comment by unicxa** [comment]
Lucky issues number 5 in binary :P

**Comment by NavidK0** [comment]
I'm pretty sure that entities can be put into a mob spawner if they're registered into Minecraft.

**Comment by Shevchik** [comment]
MobSpawners use mob names, so they can already spawn endermites, guardians and bunnies.
You just need to the mob name via API, or minecraft command.

**Comment by unicxa** [comment]
I was also going to start a plugin that implementes non vanilla/spigot values into the game its going to be based of of carbon. I'm calling it Co2-API

**Comment by NavidK0** [comment]
/setblock ~ ~ ~ minecraft:mob_spawner 0 false {EntityId:Guardian}

**Comment by NavidK0** [comment]
Confirmed working.
