### ISSUE TITLE
Banners are black in inventory

### ISSUE THREAD

**Issue by drew5494** [NavidK0/Carbon#104]
This happens with command blocks and also base colour does not work properly with command blocks

**Comment by Puremin0rez** [comment]
Can confirm, base color is always black which messes things up.

This is a good example of a banner that's spawned improperly - orange will turn to black.

http://algoin.de/bngn/?=bapu

**Comment by Shevchik** [comment]
ITem banners don't support nbt at all.

**Comment by Puremin0rez** [comment]
I understand the black banner in inventory issue, but a problem he's talking about is that banners spawned via command blocks will always have the black base color. The patterns will all be correct, but the base color won't be when placed. My banner example above is a good example of this if you put it in a command block ingame.

**Comment by Shevchik** [comment]
The /setblock command works fine for me.

**Comment by Puremin0rez** [comment]
Ah you're correct, setblock works properly. give does not.
