### ISSUE TITLE
Banners don't flap on old worlds (+ reason?)

### ISSUE THREAD

**Issue by Puremin0rez** [NavidK0/Carbon#106]
The only reason I'm making this issue is because this might be something you can workaround. So consider it a enhancement?

The apparent cause for banners not flapping is due to the stored time of the map
http://pastebin.com/Dcc4MgZQ

Perhaps the sending of what day the server is on from the server -> client can be overridden to fix this?

**Comment by Shevchik** [comment]
Time is stored as long. If that was the case then creating new map in 1.7.10 server would make the banners sway, but that doesn't happen. But i will check that anyway, maybe the problem is somewhre around it.

**Comment by Puremin0rez** [comment]
@Shevchik Actually, that's exactly what happens. Whenever I make a new world in 1.7.10 running Carbon, the banners sway. If I load up carbon on an older map from months and months ago, they don't.

**Comment by Shevchik** [comment]
Yep it works, it's just that i was deleting only region files to generate new world, not the level.dat. I have an idea why old worlds don't work. Will check it later.

**Comment by Shevchik** [comment]
So it's a fulltime int overflow after all. Mojang goddamit why ><.
