### ISSUE TITLE
mob drops

### ISSUE THREAD

**Issue by Difd9** [NavidK0/Carbon#109]
for 1.7 clients could you add a name to the blocks and items instead of half of the things being called "stone" also sorry for reporting bugs so quickly

**Comment by NavidK0** [comment]
I suppose it's something to think about for the future, but it makes things more complicated than just setting it to default block values with protocol lib.

**Comment by Difd9** [comment]
I want to look into the code that you have right now... where is the part that displays the correct item(s) to 1.7 clients

**Comment by Jikoo** [comment]
@Difd9 All 1.7 compatibility is handled in the [protocolmodifier](https://github.com/NavidK0/Carbon/tree/master/src/main/java/com/lastabyss/carbon/protocolmodifier) package. Items are handled by [ProtocolItemListener.java](https://github.com/NavidK0/Carbon/blob/master/src/main/java/com/lastabyss/carbon/protocolmodifier/ProtocolItemListener.java)
