### ISSUE TITLE
When a 1.7 client walks into a banner they bug out.

### ISSUE THREAD

**Issue by harrydevane** [NavidK0/Carbon#110]
When a 1.7 client walks into a banner they bug out and cannot easily get out of it.

**Comment by Shevchik** [comment]
Configure nocheatplus.

**Comment by roastnewt** [comment]
For your convienence:

overrideflags:
      SLIME: solid+ground
      BARRIER: solid+ground
      IRON_TRAPDOOR: solid+ground+ign_passable
      PRISMARINE: solid+ground
      SEA_LANTERN: solid+ground
      STANDING_BANNER: ground+ign_passable
      WALL_BANNER: ground+ign_passable
      RED_SANDSTONE: solid+ground
      RED_SANDSTONE_STAIRS: solid+ground
      RED_SANDSTONE_DOUBLESLAB: solid+ground
      RED_SANDSTONE_SLAB: solid+ground
      SPRUCE_FENCE_GATE: solid+ground+height150+ign_passable
      BIRCH_FENCE_GATE: solid+ground+height150+ign_passable
      JUNGLE_FENCE_GATE: solid+ground+height150+ign_passable
      DARK_OAK_FENCE_GATE: solid+ground+height150+ign_passable
      ACACIA_FENCE_GATE: solid+ground+height150+ign_passable
      SPRUCE_FENCE: solid+ground+height150
      BIRCH_FENCE: solid+ground+height150
      JUNGLE_FENCE: solid+ground+height150
      DARK_OAK_FENCE: solid+ground+height150
      ACACIA_FENCE: solid+ground+height150
      SPRUCE_DOOR_BLOCK: solid+ground+ign_passable
      BIRCH_DOOR_BLOCK: solid+ground+ign_passable
      JUNGLE_DOOR_BLOCK: solid+ground+ign_passable
      ACACIA_DOOR_BLOCK: solid+ground+ign_passable
      DARK_OAK_DOOR_BLOCK: solid+ground+ign_passable

**Comment by Matmorcat** [comment]
Thank you for that NoCheatPlus configuration. I suppose there's no way to allow jumping on slime blocks, besides disabling movement checks.
