### ISSUE TITLE
Jenkins build server missing dependency tools:jar.

### ISSUE THREAD

**Issue by mibby** [NavidK0/Carbon#111]
http://ci.citizensnpcs.co/job/Carbon/52/console

Also not building every new commit automatically?

**Comment by peteuk** [comment]
I was about to post asking where to find tools.jar
I'll add it here instead ;)

**Comment by Shevchik** [comment]
Build is triggered form the irc.
Also we added tools sources to project, so they are no longer needed. But we still need to move some files after compilation and i don't know how to do this with maven(i use ant to build carbon). Also the new builds uses instrumentation and support only linux and windows for now, so i additionally left a compile error in the project, so jenkins won't be able to build it anyway

**Comment by mibby** [comment]
http://build.true-games.org/job/Carbon/

New jenkins.
