### ISSUE TITLE
CraftMetaItem is giving compiler errors

### ISSUE THREAD

**Issue by NavidK0** [NavidK0/Carbon#112]
```

    private final ItemMeta.Spigot spigot = new ItemMeta.Spigot() {
        private boolean unbreakable;

        public void setUnbreakable(boolean setUnbreakable) {
            this.unbreakable = setUnbreakable;
        }

        public boolean isUnbreakable() {
            return this.unbreakable;
        }
    };

    public ItemMeta.Spigot spigot() {
        return this.spigot;
    }
```

That code is the specific code in question. This is because Bukkit takes priority over Spigot due to dependencies. 

Not much we can do about this to be honest, would you like to switch to Gradle?

**Comment by Shevchik** [comment]
You just need a spigot api instead of bukkit api to make it work.
Also you are using outdated build of spigot server because that argument in the constructor do exist in latest version.
Use ant to build Carbon for now.

**Comment by NavidK0** [comment]
Yeah, I have both. If I put the spigot api back on, the issues from CraftEntity with getDamage() comes back
