### ISSUE TITLE
duping bug with hoppers

### ISSUE THREAD

**Issue by 34535** [NavidK0/Carbon#113]
jenkins build #5, hoppers dupe items

i can provide more info if needed

**Comment by Shevchik** [comment]
If you have the info then write it there.

**Comment by 34535** [comment]
https://www.dropbox.com/s/2w9cmg0j7141mw7/2014-10-17_15-05-33.png?dl=0

place hoppers like in the picture and when you put an item in 1 hopper it will not disappear from the hopper you put it in, but it will transfer to the second hopper and it continues to do that until it looks like this 

https://www.dropbox.com/s/kuc95hwiim79ung/2014-10-17_15-05-42.png?dl=0

I just tested and it also does this on the  latest build #7 jenkins

and on my test server i only have the following plugins
Carbon, worldedit, plotme, permissionsex, multiverse core, multiverse inventories

**Comment by Shevchik** [comment]
It is caused by CraftItemStack instrumentation. Not really sure why, will try to find it out.

**Comment by Shevchik** [comment]
Fixed it. It was a decompiler fault and i was too lazy to check the source code.
