### ISSUE TITLE
Armor Stands leg positioned incorrectly

### ISSUE THREAD

**Issue by Puremin0rez** [NavidK0/Carbon#114]
Only one leg :)

http://i.imgur.com/RgzSfuk.jpg

**Comment by Shevchik** [comment]
IDK why it happens :(

**Comment by TheMasterBlaster** [comment]
I saw that xD I was so confused :3

**Comment by mibby** [comment]
For reference, this occurs with http://build.true-games.org/job/Carbon/9/

As of commit https://github.com/NavidK0/Carbon/commit/dc51d309932e4ebd22f0d94b9af2932c798e78ad
