### ISSUE TITLE
Mobs can be pushed(?) through gates

### ISSUE THREAD

**Issue by EbonJaeger** [NavidK0/Carbon#116]
This is slightly difficult to explain, as I am not entirely sure how they get out.
It seems that mobs do not recognize new gates for what they are, and they actively try to jump over them. While they do not seem to be able to just jump over them on their own, I think they can be "pushed" over them, such as by other mobs.
I tested this using chickens and sheep, after a bunch of cows escaped.

**Comment by EbonJaeger** [comment]
Tested more, and mobs can indeed be nudged out of 1.8 fence gates.

**Comment by NavidK0** [comment]
Carbon is no longer supported for 1.8
