### ISSUE TITLE
Banners do not sway on old worlds.

### ISSUE THREAD

**Issue by mibby** [NavidK0/Carbon#118]
Referencing the attempt-fix commit here https://github.com/NavidK0/Carbon/commit/e8bf7e0990b85048dd4f514dde13b254f4d3efce

Banners do not sway as of dev build 9 http://build.true-games.org/job/Carbon/9/, commit https://github.com/NavidK0/Carbon/commit/dc51d309932e4ebd22f0d94b9af2932c798e78ad

**Comment by TheMasterBlaster** [comment]
There is always a chance it cant be "fixed" Since vanilla Minecraft 1.8 does this. Its not something only Carbon does after all.

**Comment by mibby** [comment]
Right. Just thought I'd let @Shevchik know that the attempt-fix did not fix the issue. :)

**Comment by Shevchik** [comment]
I need your worlds level.dat files.

**Comment by mibby** [comment]
Here you go.
https://www.dropbox.com/s/q59q22bgbh5oyvh/level.dat?dl=0

**Comment by Shevchik** [comment]
Should be fixed now.
