### ISSUE TITLE
Banner lore contains 'Carbon' information.

### ISSUE THREAD

**Issue by mibby** [NavidK0/Carbon#119]
Creating a banner with a lore, it contains what I believe to be Carbon debug information in the lore? Is there any way to disable the Carbon information for a cleaner looking banner lore?

![link](http://i.imgur.com/3RzHpCb.png)

As of commit https://github.com/NavidK0/Carbon/commit/dc51d309932e4ebd22f0d94b9af2932c798e78ad
http://build.true-games.org/job/Carbon/9/

**Comment by Shevchik** [comment]
It is not a debug info. It is old banner format. It will be converted on banner place. YOu just see it now on old banners because remapping was removed.
Current banners implementation uses nbt.
