### ISSUE TITLE
Armor Stand Crafting/WorldGuard Issue

### ISSUE THREAD

**Issue by rocky143** [NavidK0/Carbon#121]
Currently, Armor stands can not be crafted as of the latest dev build #10 and when mob-spawning flag is denied in a worldguard region, armor stands can not be placed.

**Comment by Shevchik** [comment]
Armor stand is living entity so ofc worldguard blocks it spawn.
P.S. Strange mojang logic, armor stand is living entity, yet the spawn packet is the object entity one.
