### ISSUE TITLE
Carbon and GlobalMarket

### ISSUE THREAD

**Issue by sirbrando** [NavidK0/Carbon#123]
I made a ticket on GlobalMarket for this problem first, but i thought i would add it here as well incase it's a problem that can be fixed with Carbon.
## Text from GlobalMarket ticket:

The latest dev build (#13 for me) for Carbon has created an issue with Global Market, Everything seems to work except being able to buy items on the Market. An error occurs when anyone tries to do this, it takes the money out of their account but does not take down the item or send the item to their mailbox. Here is the error:
http://pastebin.com/V489m0Xd

Using Build #13 from here: 
http://build.true-games.org/job/Carbon/

This version of spigot:
http://www.spigotmc.org/threads/spigot-update-20141001a.31047/

Using b12 of GlobalMarket.

Thank you for any help you can give me.

---

I would like to note that global market worked fine with carbon until I updated it today. However the last build of carbon i use was from the 13th of october I believe.
Here's globalmarkets github: https://github.com/Dasfaust/GlobalMarket
Version of globalmarket I'm using: https://drone.io/github.com/Dasfaust/GlobalMarket/files

**Comment by Shevchik** [comment]
Looks like this problem of itemmeta not injecting strikes again.
Altrough i'm sure that i injected it properly this time.

**Comment by Shevchik** [comment]
Will try to fix it soon. Can't make new itemmeta work for some reason.

**Comment by Shevchik** [comment]
Should be fixed now.

**Comment by sirbrando** [comment]
It is working. Thank you very much.
