### ISSUE TITLE
#Build 16

### ISSUE THREAD

**Issue by externo6** [NavidK0/Carbon#125]
I know this is a dev build and probs its not suppose to work, but during testing this happens and the server shutdown:
http://pastebin.com/sNJtS8YR

**Comment by Shevchik** [comment]
Ensure that you have the latest patched spigot.

**Comment by externo6** [comment]
I am using the latest spigot patch

**Comment by Shevchik** [comment]
What OS and java version do you use?
P.S. This shouldn't happen anyway, if it happens for you that you have modified CraftItemStack.class

**Comment by externo6** [comment]
Java 8, CentOS 7
I have not modified anything

**Comment by Shevchik** [comment]
Upload your current spigot jar somewhere and send it to me.

**Comment by externo6** [comment]
https://www.dropbox.com/s/7ngjjlbs2bvmhge/spigot.jar?dl=0

**Comment by Shevchik** [comment]
I'm using the same spigot jar and everythings works for me.
Try starting your server only with carbon enabled, if it works then try searching the plugin then somehow interfieres with Carbon.

**Comment by externo6** [comment]
I have tried it with just the carbon.jar, still does not start.

**Comment by externo6** [comment]
Fresh server this works fine, ill do some more testing.

**Comment by NavidK0** [comment]
I'll try creating a new dev build, use that and see if it works.

**Comment by externo6** [comment]
Hi, it only works as the root user.
We do not start the server using the root user due to security etc

**Comment by NavidK0** [comment]
The plugin needs to be able to create carbonAgent.jar. I can move this agent to a different directory and see if that works.

**Comment by externo6** [comment]
What directory does it create it in?

**Comment by NavidK0** [comment]
It creates the file in a temporary directory.

**Comment by externo6** [comment]
Issue starts on and after this commit https://github.com/NavidK0/Carbon/commit/949e55834c19011fa0e191667e707cc03e98e0fe

**Comment by Shevchik** [comment]
Have you tried the latest build? We moved file to the server folder.

**Comment by externo6** [comment]
Yes, build 23

**Comment by NavidK0** [comment]
Could you post your entire log file?

**Comment by NavidK0** [comment]
Oh, and in the config, enable verbose mode.

**Comment by externo6** [comment]
With Verbose true
http://pastebin.com/ZRVtDF95

We use tmux, without the use of tmux it works.
We have also tested with Screen.

**Comment by Shevchik** [comment]
That means that agent is unable to load properly for some reason.
Can't really help here, agent load is not easy.
P.S. Does it work with screen or not?

**Comment by externo6** [comment]
Ok we have found the problem, we use a custom logging xml, using: -Dlog4j.configurationFile=log4j2.xml at the java invocation. Removing this line allows carbon to work.

**Comment by NavidK0** [comment]
Yeah, the plugin needs total access to the JVM in order to work properly. It heavily modifies how the internals of Bukkit works, and needs to instrumentate the JVM to do it. This is why plugin loaders and some programs that modify the JVM won't work with Carbon. Thank you for this issue though, it gives more insight on what works and doesn't work.
