### ISSUE TITLE
Users on 1.7 kicked from the server.

### ISSUE THREAD

**Issue by freestyler989** [NavidK0/Carbon#126]
Hi,

I've been trying out Carbon on my local servers for many days now, everything worked very well. But as I installed it on my server, players on 1.7 can't join the server anymore. They're instantly kicked with the error: "Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 68"
Could it be a plugin which is causing this?
On my local servers, everything works like a charm.

Thanks in advance.

**Comment by Shevchik** [comment]
For some reason worldborder packet is not filtering. Anyway we release carbon 1.7 soon, so you should just wait.

**Comment by freestyler989** [comment]
Thank you very much :)

**Comment by freestyler989** [comment]
Edit: Could the plugin WorldBorder cause this? If so, I'll just remove it until the problem was resolved...

**Comment by Shevchik** [comment]
No it can't.
