### ISSUE TITLE
Inconsistencies in Spigot or NCP one.

### ISSUE THREAD

**Issue by R-Mule** [NavidK0/Carbon#127]
So I have gotten this warning: WARN DataMan inconsistencies: wrong number of online players (19 instead of 18)

For a day or so now, but only on my main server, which is where I have the protocol blocker installed. And I noticed something. When 1.7 players try to join, something in the way they are added to the list of online players then removed instantly is creating this problem. Which has to be the protocol blocker doing it. As on my dev server it is not there. Obviously I force all players to run 1.8, but for those who attempt it, this will still occur. 

Its not horrible and not doing any harm to TPS or Memory that I can note as of yet. However it is quite the console spammer. I turned off the feature in NCP that allegedly cause this spam, it did not fix it.

**Comment by Shevchik** [comment]
Install protocollib

**Comment by R-Mule** [comment]
This appears to have resolved the issues described! I will post back if I see it again! Thanks!
