### ISSUE TITLE
Server closing from crash

### ISSUE THREAD

**Issue by externo6** [NavidK0/Carbon#128]
Server started fine, but within seconds of logging in server crashes with this:
http://pastebin.com/6n6JaLii
http://pastebin.com/9FxpuFmP

**Comment by Shevchik** [comment]
This means that you are not using latest spigot somehow.

**Comment by externo6** [comment]
Oh Ye sorry I may not be on that server, ill report back in a sec!

**Comment by externo6** [comment]
Yes fixed, sorry my bad. Sorry for wasting your time.
