### ISSUE TITLE
Doors not stacking

### ISSUE THREAD

**Issue by MineRealm** [NavidK0/Carbon#130]
In Minecraft 1.8, doors should be stackable to 64. Users are currently unable to stack doors in their inventory, using Carbon 1.7.

**Comment by Matmorcat** [comment]
I can confirm this is true for only the default oak doors. It only happens while not in creative mode as well. The items appear to stack for a split second and then unstack (the product of the client assuming the doors should stack).

**Comment by NavidK0** [comment]
This is because the default doors are not modified by Carbon, therefore, remain the same.

**Comment by starg09** [comment]
Could you modify them then? :-P

**Comment by k3ldon** [comment]
i think is with essencials

**Comment by NavidK0** [comment]
I won't fix this for now, I don't want to break compatibility with other plugins until I can be sure as to why custom doors won't work correctly with LWC.

**Comment by starg09** [comment]
Ok, although keep in mind that I don't use lwc, yet I don't seem able to
stack oak or iron doors. I think someone suggested a conflict with
essentials...
