### ISSUE TITLE
Layers for banners are not in the order they are crafted to be.

### ISSUE THREAD

**Issue by Matmorcat** [NavidK0/Carbon#131]
What happened was that I tried to make the U.S. flag and found out it is not possible to make with Carbon.

What I did:
Took a white banner from the creative inventory
Dyed on 4 red stripes (2 rose red in the top right and left corners, 2 rose red in the middle row right and left slots, and the white banner in the middle slot)
Dyed that banner with 1 lapis lazuli in the top right corner and the banner in the middle slot.

What should've happened: A decent american flag should have been made.
What actually happened: The blue square in the top right appeared behind the red lines and ran over the blue corner, leaving a somewhat correct flag, but with red lines running through the place where the stars would go.

The layering for flags is not completely accurate. I also tried doing the blue in the top right corner before the red stripes and it ended up with the same result.

**Comment by Shevchik** [comment]
Will fix it later. It is due to hash map losing order of elements.

**Comment by Shevchik** [comment]
Latest build should now preserve banners patterns order
