### ISSUE TITLE
Carbon doesn't start properly

### ISSUE THREAD

**Issue by freestyler989** [NavidK0/Carbon#132]
Since the new update came out, Carbon doesn't start anymore.
I'm using the latest version (1.7) on Spigot Build 1649 patched with Spigot Patcher.
Link to console error: http://pastebin.com/gaQygZG8

Thanks in advance.

**Comment by Shevchik** [comment]
Ensure that you have the latest spigot patch and not using options like bind later in spigot config.

**Comment by freestyler989** [comment]
Thank you very much. Everything seems to be working for the moment :)
