### ISSUE TITLE
Armor Stands don't fire EntityDamageByEntityEvent

### ISSUE THREAD

**Issue by Puremin0rez** [NavidK0/Carbon#133]
This is a really bad issue because protection plugins can't provide support for armor stands, allowing players to break them in other regions.

Armor stands do fire PlayerInteractEntity event, however that event only handles right click. I've stopped people from stealing armor stand contents, but of course they can still just break them ;)

**Comment by NavidK0** [comment]
This is because there are no craftbukkit methods in the Armor Stand classes. This can be fixed fairly easily.

**Comment by Shevchik** [comment]
They should now do this.
