### ISSUE TITLE
Server Shuts Down After 30 Seconds

### ISSUE THREAD

**Issue by Jordio94** [NavidK0/Carbon#135]
Carbon 1.6.3 was working working fine but as soon as I updated to Carbon 1.7, the server crashes after about 30 seconds with the error 'Exception in server tick loop'. Switching back to 1.6.3 makes everything work fine again so the problem is only with 1.7. I've tried this on both my public and private servers and get the same result. No other plugins or settings have changed and I'm still using the latest Spigot build.

**Comment by Shevchik** [comment]
Update to latest patched spigot.
