### ISSUE TITLE
Repairing items with color tags strips them of color

### ISSUE THREAD

**Issue by justwheel** [NavidK0/Carbon#136]
A few players on my server reported that after they tried repairing items with colored title and lore tags in an anvil, they were stripped of their colors, leaving the default text instead of the colors.

I imagine this is a possible conflict with either Essentials or Spigot itself? In either case, I am using Essentials Dev2.14.98 and the latest Spigot patch released.

If any more information is needed, I would be happy to provide it. Just wasn't sure all that would be needed for a bug report of this nature.

**Comment by Jikoo** [comment]
That's actually a vanilla issue to the best of my knowledge, I've never been able to repair items with colored names on 1.7 at all.

**Comment by NavidK0** [comment]
I'm not quite sure if we should fix this... if it's not fixed in Vanilla, is it an intended feature?

(It's probably an oversight, but still...)

**Comment by justwheel** [comment]
@Jikoo: Before using Carbon 1.7, my players were able to repair colored items in anvils. I will ask around my server for more information, but this is what has been reported to me. Also, this is making me wonder if there is a conflict with Essentials in some way?

**Comment by Jikoo** [comment]
@jflory7 I'm certain that's another plugin modifying anvils and not Essentials, I run Essentials as well, and NMS is required to obtain the name typed into the anvil GUI. Could be an issue with my plugins, I'll use a plugin to spawn colored named items, stop and remove all plugins, then try renaming.

Edit: Just tested with 0 plugins, repairing items with colored names strips the section sign. Can't easily test on smp vanilla without mcedit/copying world data, but at very least it is not default Bukkit/Spigot behavior.

**Comment by NavidK0** [comment]
I test this in single player using an item spawner mod, colored items are not carried over. It's not Vanilla behavior. Now, the plugin that you are using that allows for the transfer of colored enchants likely modifies the end result of the enchant.

**Comment by Shevchik** [comment]
But spigot carries color codes after enchant so we will still have to fix it.

**Comment by Jikoo** [comment]
@Shevchik Spigot does not. See my previous post, I tested it with 0 plugins.

**Comment by Shevchik** [comment]
Oh shi..... Don't know what should i actually do now...

**Comment by NavidK0** [comment]
This is not default vanilla behavior. Our enchanting api will likely have to be changed to allow for other plugins to modify the end result, but by that time we figure it out, Spigot 1.8 might already come out.
