### ISSUE TITLE
ProtocolBlocker not properly blocking protocols?

### ISSUE THREAD

**Issue by justwheel** [NavidK0/Carbon#137]
Not sure if this is an issue with Carbon itself or not, but it seems that there is a problem with blocking users on 1.7 clients after I updated to Carbon 1.7.

Previously, players on older versions of Minecraft were properly rejected, but now I've noticed in my console that players who join on older clients are kicked, but they are also registered in-game and mess up other plugins such as NoCheatPlus. For example, my console is now spammed with this NCP error persistantly:
`[12:54:38 WARN]: [NoCheatPlus] DataMan inconsistencies: wrong number of online players (14 instead of 9)`
When this specific error was fired, I had six people online.

I never noticed this prior to using Carbn 1.7, and I have not updated any plugins recently outside of Carbon, which is why I'm inclined to believe that it is related.

**Comment by Shevchik** [comment]
Install protocollib.

**Comment by justwheel** [comment]
@Shevchik: Is installing ProtocolLib mandatory now? If it is, what's the point of even having the ProtocolBlocker in the first place? Why were improvements made to the protocol blocker when it is not necessary?

I really think more info is needed on this than just a "Add another plugin" resolution…

**Comment by justwheel** [comment]
This is a really frustrating resolution as there is strong evidence to show that this is a bug in one of the plugin's features, and if this is the type of resolution given to bugs of this nature, then it doesn't make sense to have a broken feature in the plugin… perhaps @NavidK0 can offer some insight into this then.

**Comment by justwheel** [comment]
As Shevchik told me on the Spigot forums:
"Carbon can only kick player on join event without protocollib. And this causes issues.
I'm working on porting it to carbon nettyinjector, but currently you still need protocollib."

This makes more sense now. That would have been the better answer than the two-word answer given, but nonetheless, this issue makes sense now. Thanks.
