### ISSUE TITLE
[Bug] Odd torch behavior.

### ISSUE THREAD

**Issue by mibby** [NavidK0/Carbon#14]
Compiled source as of commit https://github.com/NavidK0/Carbon/commit/0da8f35147fc1efd4dec38482b1917617485f908

Torches are behaving oddly. They are not rotated correctly on blocks. 

This is a place in my world that has torches floating.
![link](http://i.imgur.com/EpTUXwM.png)

This occurs every once in a while when trying to place a torch on the wall. It floats in the wrong direction.
![link2](http://i.imgur.com/rIXhORg.png)

Some players are reporting they are able to dupe torches when it floats, but might be clientside only until they relog.

**Comment by mibby** [comment]
@NavidK0 

![link2](http://i.imgur.com/SVOOxxc.png)

I think I narrowed it down some. When crafting torches (stick + coal), placing the newly crafted torches on the ground causes them to float and at an angle. It also does not use up the stack at all, causing infinite torches.

**Comment by mibby** [comment]
@NavidK0 Torch recipe is extremely broken with this commit. I can keep spam clicking to spawn in arrows.
https://github.com/NavidK0/Carbon/commit/a15fed6884edda2436f453c991c15f556e8787a8

![link5](http://i.imgur.com/nPH9Q0Y.png)

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by mibby** [comment]
Confirmed fixed. Can create torches properly again, jack-o-lanterns, and not noticing any more issues with floating torches when placing newly crafted ones down.

Though, there are issues with floating torches already existing in the world still. Not sure if there is much you can do about that. Torches that are suppose to be on a block, but rotated 180 degrees, floating instead of hanging. Breaking the block the torch is suppose to be on breaks the torch.

I will let you know if there are still issues with newly placed torches floating.
