### ISSUE TITLE
Carbon will not load, server shuts down

### ISSUE THREAD

**Issue by ghost** [NavidK0/Carbon#141]
I can not seem to get carbon to load with the latest version 1.7. I have the latest protocollib for 1.8 spigot loaded, and i even tried the lastest builds from the jenkins repo, here is my error output, and then my server stops itself. 

http://hastebin.com/yotegekuxa.txt

**Comment by Shevchik** [comment]
Use latest spigot patch and stop using late bind option.

**Comment by ghost** [comment]
ahh late bind i will turn that off and see if it works.

Am I not using the latest patch? I have been using this one i thought - http://www.spigotmc.org/threads/spigot-update-20141001a.31047/

**Comment by Shevchik** [comment]
This problem happens if you are not using latest spigot patch or using late bind option.
So that is why i answered that.

**Comment by ghost** [comment]
Okay cool just making sure, thanks for the help!
