### ISSUE TITLE
As of Carbon dev build #32 banners no longer wave on old worlds as before.

### ISSUE THREAD

**Issue by SequaciousGAMES** [NavidK0/Carbon#142]
Title says it all. Not tested in earlier versions.

**Comment by Shevchik** [comment]
Still wave for me even in old worlds.
I need your world level.dat

**Comment by SequaciousGAMES** [comment]
I had 3 and was unsure which you wanted.
There's
level.dat_old
level.dat_mcr
level.dat
And how would I go about sending you these? Would via dropbox be okay?

**Comment by Shevchik** [comment]
I don't need them anymore.
I found the root cause of this >_<.
Banners sway time limit depends on banner position in world. The closer you to the border the lower world time limit is. Starting from some coords it will overflow anyway >_<.
I need a complex fix for that.

**Comment by NavidK0** [comment]
Why the heck didn't Mojang just base banner time off of server ticks instead of world time???

**Comment by SequaciousGAMES** [comment]
Oh I see, glad this issue wasn't just me being an idiot. Sucks that Mojang made it so awkward.

**Comment by Shevchik** [comment]
Looks like i gonna need some advanced math to fix that.

**Comment by Shevchik** [comment]
Unfortunately i can't fix that. Too much advanced math needed because i should calculate a time value that will make all banner in player view distance sway which will take too much server resources for a small feature like that. I'm not even sure if finding that value is possible in all cases.
