### ISSUE TITLE
snow golem

### ISSUE THREAD

**Issue by k3ldon** [NavidK0/Carbon#144]
not spawn when i put the blocks...

Carbon v1.7
Spigot 20141001a

**Comment by Jikoo** [comment]
I can't replicate this, are you placing the pumpkin last?

**Comment by k3ldon** [comment]
yeap http://puu.sh/cmPJ5/ab950fe651.png

**Comment by k3ldon** [comment]
any help?

**Comment by k3ldon** [comment]
fixed in the last version !
