### ISSUE TITLE
Shuts down after 30 seconds: Even with tips

### ISSUE THREAD

**Issue by cocokat1** [NavidK0/Carbon#147]
YES I have the latest spigot patch YES I have the recommended ProtocalLIB.

Here is my error in console:

23.10 22:03:12 [Server] ERROR This crash report has been saved to: /./crash-reports/crash-2014-10-23_22.03.12-server.txt
23.10 22:03:12 [Server] INFO at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-1649.jar:git-Spigot-1649]
23.10 22:03:12 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot-1649.jar:git-Spigot-1649]
23.10 22:03:12 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) ~[spigot-1649.jar:git-Spigot-1649]
23.10 22:03:12 [Server] INFO at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) ~[spigot-1649.jar:git-Spigot-1649]
23.10 22:03:12 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:723) ~[spigot-1649.jar:git-Spigot-1649]
23.10 22:03:12 [Server] INFO at net.minecraft.server.v1_7_R4.EntityTracker.updatePlayers(EntityTracker.java:153) ~[spigot-1649.jar:git-Spigot-1649]
23.10 22:03:12 [Server] INFO at net.minecraft.server.v1_7_R4.EntityTrackerEntry.track(EntityTrackerEntry.java:130) ~[spigot-1649.jar:git-Spigot-1649]
23.10 22:03:12 [Server] INFO java.lang.NoSuchMethodError: net.minecraft.server.v1_7_R4.PacketPlayOutEntityTeleport.<init>(IIIIBBZZ)V
23.10 22:03:12 [Server] ERROR Encountered an unexpected exception

Here is my crash report:

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 10/23/14 10:05 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.server.v1_7_R4.PacketPlayOutEntityTeleport.<init>(IIIIBBZZ)V
    at net.minecraft.server.v1_7_R4.EntityTrackerEntry.track(EntityTrackerEntry.java:130)
    at net.minecraft.server.v1_7_R4.EntityTracker.updatePlayers(EntityTracker.java:153)
    at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:723)
    at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
    at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Linux (amd64) version 3.8.0-36-generic
    Java Version: 1.7.0_71, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1981684320 bytes (1889 MB) / 2594897920 bytes (2474 MB) up to 2594897920 bytes (2474 MB)
    JVM Flags: 11 total; -Xmx2560M -Xms2560M -Xss2M -XX:PermSize=50m -XX:MaxPermSize=150m -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalMode -XX:+CMSIncrementalPacing -XX:+CMSParallelRemarkEnabled -XX:MaxGCPauseMillis=50
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 15, tcache: 0, allocated: 13, tallocated: 95
    CraftBukkit Information: 
   Running: CraftBukkit version git-Spigot-1649 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT) true
   Plugins: { GroupManager v2.1.31 (Phoenix) org.anjocaido.groupmanager.GroupManager [AnjoCaido, Gabriel Couto, ElgarL], SmokeTrail v7.3 me.dimension.smoke.trail [DimensioX(King Magnus)], WorldEdit v5.6.3 com.sk89q.worldedit.bukkit.WorldEditPlugin [], ProtocolBlocker v1.1.0 be.maximvdw.protoblock.ProtocolBlocker [Maximvdw], BetterBackpacks v1.2.5 info.trentech.BetterBackpacks.BetterBackpacks [], Vault v1.4.1-b436 net.milkbowl.vault.Vault [cereal, Sleaker, mung3r], Lockette v1.7.12 org.yi.acru.bukkit.Lockette.Lockette [Acru], ProtocolLib v3.6.0-SNAPSHOT com.comphenix.protocol.ProtocolLibrary [Comphenix], LogBlock v1.80 de.diddiz.LogBlock.LogBlock [DiddiZ, md_5, ammar2, frymaster], mcMMO v1.5.00-b3547 com.gmail.nossr50.mcMMO [nossr50, GJ, NuclearW, bm01, Glitchfinder, TfT_02, t00thpick1, Riking], WorldGuard v6.0.0-beta-02 com.sk89q.worldguard.bukkit.WorldGuardPlugin [], Essentials vPre2.14.1.3 com.earth2me.essentials.Essentials [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally], SilkSpawners v3.5.1 de.dustplanet.silkspawners.SilkSpawners [xGhOsTkiLLeRx, mushroomhostage], EssentialsProtect vPre2.14.1.3 com.earth2me.essentials.protect.EssentialsProtect [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits], SignChestShop v1.3.6 co.technius.signchestshop.SignChestShopPlugin [Technius], LibsDisguises v8.2.6 me.libraryaddict.disguise.LibsDisguises [libraryaddict], EssentialsSpawn vPre2.14.1.3 com.earth2me.essentials.spawn.EssentialsSpawn [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits], CraftBay v1.2.8 edu.self.startux.craftBay.CraftBayPlugin [StarTux], Carbon v1.7 com.lastabyss.carbon.Carbon [Navid K., _Shevchik_, Aust1n46], ChestShop v3.7.17 com.Acrobot.ChestShop.ChestShop [Acrobot], EssentialsChat vPre2.14.1.3 com.earth2me.essentials.chat.EssentialsChat [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Okamosy, Iaccidentally], EssentialsAntiBuild vPre2.14.1.3 com.earth2me.essentials.antibuild.EssentialsAntiBuild [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, Iaccidentally], EnjinMinecraftPlugin v2.7.0 com.enjin.officialplugin.EnjinMinecraftPlugin [www.Enjin.com], DisguiseCraft v1.1 pgDev.bukkit.DisguiseCraft.DisguiseCraft [libraryaddict],}
   Warnings: DEFAULT
   Threads: { TIMED_WAITING Server Infinisleeper: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_7_R4.ThreadSleepForever.run(SourceFile:63)], RUNNABLE Netty IO #0: [sun.nio.ch.EPollArrayWrapper.epollWait(Native Method), sun.nio.ch.EPollArrayWrapper.poll(Unknown Source), sun.nio.ch.EPollSelectorImpl.doSelect(Unknown Source), sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), net.minecraft.util.io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:591), net.minecraft.util.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:301), net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Timer-0: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], TIMED_WAITING Craft Scheduler Thread - 10: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING Finalizer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)], TIMED_WAITING MySQL Connection Reaper Thread - LogBlock: [java.lang.Thread.sleep(Native Method), de.diddiz.util.MySQLConnectionPool$ConnectionReaper.run(MySQLConnectionPool.java:103), java.lang.Thread.run(Unknown Source)], RUNNABLE Attach Listener: [], TIMED_WAITING Snooper Timer: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], RUNNABLE Craft Scheduler Thread - 14: [java.net.PlainSocketImpl.socketConnect(Native Method), java.net.AbstractPlainSocketImpl.doConnect(Unknown Source), java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source), java.net.AbstractPlainSocketImpl.connect(Unknown Source), java.net.SocksSocketImpl.connect(Unknown Source), java.net.Socket.connect(Unknown Source), java.net.Socket.connect(Unknown Source), sun.net.NetworkClient.doConnect(Unknown Source), sun.net.www.http.HttpClient.openServer(Unknown Source), sun.net.www.http.HttpClient.openServer(Unknown Source), sun.net.www.http.HttpClient.<init>(Unknown Source), sun.net.www.http.HttpClient.New(Unknown Source), sun.net.www.http.HttpClient.New(Unknown Source), sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source), sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source), sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source), sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source), com.earth2me.essentials.metrics.Metrics.postPlugin(Metrics.java:481), com.earth2me.essentials.metrics.Metrics.access$400(Metrics.java:43), com.earth2me.essentials.metrics.Metrics$1.run(Metrics.java:224), org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71), org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING Reference Handler: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:503), java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)], RUNNABLE Craft Scheduler Thread - 13: [java.net.SocketInputStream.socketRead0(Native Method), java.net.SocketInputStream.read(Unknown Source), java.net.SocketInputStream.read(Unknown Source), sun.security.ssl.InputRecord.readFully(Unknown Source), sun.security.ssl.InputRecord.read(Unknown Source), sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source), sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source), sun.security.ssl.AppInputStream.read(Unknown Source), java.io.BufferedInputStream.fill(Unknown Source), java.io.BufferedInputStream.read1(Unknown Source), java.io.BufferedInputStream.read(Unknown Source), sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source), sun.net.www.http.HttpClient.parseHTTP(Unknown Source), sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source), sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source), com.enjin.officialplugin.EnjinMinecraftPlugin.testHTTPSconnection(EnjinMinecraftPlugin.java:1612), com.enjin.officialplugin.threaded.PeriodicEnjinTask.run(PeriodicEnjinTask.java:79), org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71), org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Craft Scheduler Thread - 15: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Craft Scheduler Thread - 12: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE Netty IO #1: [sun.nio.ch.EPollArrayWrapper.epollWait(Native Method), sun.nio.ch.EPollArrayWrapper.poll(Unknown Source), sun.nio.ch.EPollSelectorImpl.doSelect(Unknown Source), sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), net.minecraft.util.io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:591), net.minecraft.util.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:301), net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Spigot Watchdog Thread: [java.lang.Thread.sleep(Native Method), org.spigotmc.WatchdogThread.run(WatchdogThread.java:92)], RUNNABLE Server thread: [java.lang.Thread.dumpThreads(Native Method), java.lang.Thread.getAllStackTraces(Unknown Source), org.bukkit.craftbukkit.v1_7_R4.CraftCrashReport.call(CraftCrashReport.java:28), net.minecraft.server.v1_7_R4.CrashReportSystemDetails.a(SourceFile:74), net.minecraft.server.v1_7_R4.CrashReport.h(CrashReport.java:45), net.minecraft.server.v1_7_R4.CrashReport.<init>(CrashReport.java:33), net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:510), net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)], TIMED_WAITING Spigot Metrics Thread: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], RUNNABLE DestroyJavaVM: [], TIMED_WAITING File IO Thread: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_7_R4.FileIOThread.b(SourceFile:44), net.minecraft.server.v1_7_R4.FileIOThread.run(SourceFile:23), java.lang.Thread.run(Unknown Source)], RUNNABLE Signal Dispatcher: [], WAITING Thread-5: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), net.minecraft.util.com.mojang.util.QueueLogAppender.getNextLogEvent(QueueLogAppender.java:73), org.bukkit.craftbukkit.v1_7_R4.util.TerminalConsoleWriterThread.run(TerminalConsoleWriterThread.java:25), java.lang.Thread.run(Unknown Source)], TIMED_WAITING pool-8-thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE Server console handler: [java.io.FileInputStream.readBytes(Native Method), java.io.FileInputStream.read(Unknown Source), java.io.BufferedInputStream.fill(Unknown Source), java.io.BufferedInputStream.read(Unknown Source), java.io.FilterInputStream.read(Unknown Source), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader$1.read(ConsoleReader.java:167), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:267), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:204), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readCharacter(ConsoleReader.java:995), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLineSimple(ConsoleReader.java:1506), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:1153), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:1117), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:1105), net.minecraft.server.v1_7_R4.ThreadCommandReader.run(ThreadCommandReader.java:34)], WAITING Java2D Disposer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.ReferenceQueue.remove(Unknown Source), sun.java2d.Disposer.run(Unknown Source), java.lang.Thread.run(Unknown Source)],}
   Recent tasks from 1171-1201{EnjinMinecraftPlugin:com.enjin.officialplugin.threaded.PeriodicEnjinTask@1229,WorldEdit:com.sk89q.worldedit.bukkit.SessionTimer@1229,LogBlock:de.diddiz.LogBlock.Consumer@1229,EnjinMinecraftPlugin:com.enjin.officialplugin.tpsmeter.MonitorTPS@1229,}
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 0 / 50; []
    Is Modded: Definitely; Server brand changed to 'Spigot'
    Type: Dedicated Server (map_server.txt)

Here is a plugin list:

23.10 22:06:59 [Server] INFO Plugins (24): GroupManager, SmokeTrail, WorldEdit, ProtocolBlocker, BetterBackpacks, Vault, Lockette, ProtocolLib, LogBlock, mcMMO, WorldGuard, Essentials, SilkSpawners, EssentialsProtect, SignChestShop, LibsDisguises, EssentialsSpawn, CraftBay, Carbon, ChestShop, EssentialsChat, EssentialsAntiBuild, EnjinMinecraftPlugin, DisguiseCraft

And here is my spigot.yml, if it's any use...
# This is the main configuration file for Spigot.
# As you can see, there's tons to configure. Some options may impact gameplay, so use
# with caution, and make sure you know what each option does before configuring.
# For a reference for any variable inside this file, check out the Spigot wiki at
# http://www.spigotmc.org/wiki/spigot-configuration/
# 
# If you need help with the configuration or have any questions related to Spigot,
# join us at the IRC or drop by our forums and leave a post.
# 
# IRC: #spigot @ irc.spi.gt ( http://www.spigotmc.org/pages/irc/ )
# Forums: http://www.spigotmc.org/

config-version: 8
settings:
  debug: false
  save-user-cache-on-stop-only: false
  bungeecord: false
  late-bind: false
  sample-count: 12
  player-shuffle: 0
  filter-creative-items: true
  user-cache-size: 1000
  int-cache-limit: 1024
  moved-wrongly-threshold: 0.0625
  moved-too-quickly-threshold: 100.0
  timeout-time: 60
  restart-on-crash: true
  restart-script: RUN.bat
  netty-threads: 4
  attribute:
    maxHealth:
      max: 2048.0
    movementSpeed:
      max: 2048.0
    attackDamage:
      max: 2048.0
  global-api-cache: false
messages:
  whitelist: We are fixing the server, it is currently offline.
  unknown-command: That's not a command, silly!
  server-full: The server is full, get access by buying a VIP add-on.
  outdated-client: Outdated client! Please use {0}
  outdated-server: Outdated server! I'm still on {0}
  restart: The server is Restarting.
commands:
  tab-complete: 0
  spam-exclusions:
- /skill
  silent-commandblock-console: false
  replace-commands:
- setblock
- summon
- testforblock
- tellraw
  log: true
  stats:
  disable-saving: false
  forced-stats: {}
  world-settings:
  default:
    verbose: true
    mob-spawn-range: 4
    anti-xray:
      enabled: true
      engine-mode: 1
      hide-blocks:
      - 14
      - 15
      - 16
      - 21
      - 48
      - 49
      - 54
      - 56
      - 73
      - 74
      - 82
      - 129
      - 130
      replace-blocks:
      - 1
      - 5
    nerf-spawner-mobs: false
    growth:
      cactus-modifier: 100
      cane-modifier: 100
      melon-modifier: 100
      mushroom-modifier: 100
      pumpkin-modifier: 100
      sapling-modifier: 100
      wheat-modifier: 100
    entity-activation-range:
      animals: 32
      monsters: 32
      misc: 16
    entity-tracking-range:
      players: 48
      animals: 48
      monsters: 48
      misc: 32
      other: 64
    hopper-alt-ticking: false
    ticks-per:
      hopper-transfer: 8
      hopper-check: 8
    hopper-amount: 1
    random-light-updates: false
    save-structure-info: true
    max-bulk-chunks: 5
    max-entity-collisions: 8
    dragon-death-sound-radius: 0
    seed-village: 10387312
    seed-feature: 14357617
    hunger:
      walk-exhaustion: 0.2
      sprint-exhaustion: 0.8
      combat-exhaustion: 0.3
      regen-exhaustion: 3.0
    max-tnt-per-tick: 100
    view-distance: 10
    chunks-per-tick: 650
    clear-tick-list: false
    merge-radius:
      exp: 3.0
      item: 2.5
    item-despawn-rate: 6000
    arrow-despawn-rate: 1200
    enable-zombie-pigmen-portal-spawns: true
    wither-spawn-sound-radius: 0
    hanging-tick-frequency: 100
    zombie-aggressive-towards-villager: true

PLEASE HELP ME!  I AM PULLING HAIR OUT FOR THIS UPDATE!

**Comment by Jikoo** [comment]
http://hastebin.com/ :V

**Comment by NavidK0** [comment]
The error literally means that your version of Spigot doesn't have the new methods in http://pancakeurl.com/spigot/ the latest patch released on October 1st. That's what it means, word for word. There's only two possibilities, one, you have late-bind enabled, which you clearly do not, and two, you don't have the latest patch of Spigot.

Are you using a server panel of some sorts? Have you made sure that the newest spigot jar is actually loading in said panel? That may be the problem.

**Comment by cocokat1** [comment]
Thanks a lot, I just have never been brought to that page before just the Jenkins that had the latest build...
