### ISSUE TITLE
Armour Stands Are Not Craftable

### ISSUE THREAD

**Issue by Hostile9876** [NavidK0/Carbon#150]

**Comment by NavidK0** [comment]
That's it? No other information? Build of carbon... spigot version... client version.... etc?

We could use some more information, because clearly the recipe is added with this code:

```
ShapedRecipe armorStand = new ShapedRecipe(new ItemStack(this.armorStandEntityMat)).shape(new String[] {"iii", " i ", "isi"}).setIngredient('i', Material.STICK).setIngredient('s', Material.STEP);
      addRecipe(armorStand);
```

in Injector.class with this shape:
[stick] [stick] [stick]
[empty] [stick] [empty]
[stick] [step] [stick]

**Comment by NavidK0** [comment]
No further info given. Closing.
