### ISSUE TITLE
Piston +  slimeblock =/= Launch 

### ISSUE THREAD

**Issue by RawrUniversal** [NavidK0/Carbon#151]
Piston and slimeblocks don't launch entities

**Comment by k3ldon** [comment]
the same, confirmed with build 42 and with build 40 works

**Comment by NavidK0** [comment]
<strike>We're likely never going to fix this, since Spigot 1.8 is literally coming in about less than three weeks.</strike>

Forget what I said earlier.

**Comment by Shevchik** [comment]
:D

**Comment by RawrUniversal** [comment]
So will you fix it or not?

**Comment by Shevchik** [comment]
At least we will try

**Comment by RawrUniversal** [comment]
Ok Thanks!

**Comment by Shevchik** [comment]
Fixed
