### ISSUE TITLE
Error when starting server causing shutdown

### ISSUE THREAD

**Issue by PhanaticD** [NavidK0/Carbon#152]
Server starts but once it hits "done!" it turns off as if I had done /stop

http://pastebin.com/83YNiLkv

**Comment by PhanaticD** [comment]
Carbon dev build 39 and yes I am using latest spigot patch and protocollib for spigot 1.8

**Comment by Jikoo** [comment]
Disable late bind

**Comment by PhanaticD** [comment]
late bind is not enabled

**Comment by Jikoo** [comment]
Starting fine for me with build 39. Have you tried deleting plugins/Carbon/ and letting it regenerate?

**Comment by NavidK0** [comment]
This issue happened with one other person before, I'm looking for the issue opened... it could shed some light on this.

**Comment by PhanaticD** [comment]
yes I have tried deleting the Carbon folder

im using java 8u20 if that matters

**Comment by Jikoo** [comment]
Java 8u10 here, I should really update >.> Running Debian 7, the only time I had an issue was when the user running the server was not the user who had downloaded Carbon.jar and permissions were slightly messed up.

**Comment by Shevchik** [comment]
Last time that was because somebody was using custom log4j config. Remove all your JVM startup flags and see if it will help.

**Comment by PhanaticD** [comment]
ah yea I do use a custom log4j to remove colors from the log files

**Comment by PhanaticD** [comment]
Do I have to remove it or can something be changed in the plugin?
