### ISSUE TITLE
New blocks stopped generating in Carbon 1.7

### ISSUE THREAD

**Issue by rlf** [NavidK0/Carbon#153]
Hi.

Not sure how to report this (i.e. include enough information for you to fix it).

a) I was running with the Carbon 1.6.1 and latest spigot-patch, created an 1.8 world using multiverse, and all was good (Diorite and Andesite + rabbits in the new world).
b) I updated to the latest Carbon 1.7, and created a new 1.8 world.
This new world does not have rabbits, and does not have andesite or diorite.

Bonus info: I don't have dynmap, I don't have "late-bind", I have:

```
[INFO] This server is running CraftBukkit version git-Spigot-1.7.9-R0.2-207-g03373bb (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
```

and

```
1:53:11 PM CONSOLE: [INFO] --=======Carbon=======--
1:53:11 PM CONSOLE: [INFO] Version: 1.8
1:53:11 PM CONSOLE: [INFO] Authors: Navid K., _Shevchik_, Aust1n46
1:53:11 PM CONSOLE: [INFO] Other contributors: pupnewfster, Stefenatefun, Jikoo, Wombosvideo, mcmonkey4eva, sickray34s
1:53:11 PM CONSOLE: [INFO] IRC: irc.esper.net
1:53:11 PM CONSOLE: [INFO] Channel: #Carbon
1:53:11 PM CONSOLE: [INFO] Page: http://www.spigotmc.org/resources/carbon.1258/
```

I've tried deleting the world, and recreating it numereous times, but the generator seems to NOT be "carbonized".

Is there any way I can force it?

PS: I also have multiple other plugins in play, PlotMe and uSkyBlock among others - but as I started with, it worked "fine" in 1.6.1.

**Comment by Shevchik** [comment]
Something clearing up the generators. We inject them on world init now, not at plugin load. Try installing carbon only.

**Comment by Shevchik** [comment]
Also check your configuration, maybe you don't have any worlds in generator attch list.

**Comment by rlf** [comment]
Aah, most likely the last comment - Will check ASAP.

**Comment by rlf** [comment]
Yup, I had missed that the 1.8 world was gone from the world list.
My bad - closing this issue.

And thanks for solving it @Shevchik
