### ISSUE TITLE
Item Frames do not output power on certain axises

### ISSUE THREAD

**Issue by tnytown** [NavidK0/Carbon#154]
Item Frames facing West hooked up to comparators do not give off power.
This is not present in Vanilla.
http://imgur.com/ztwr3rU (vanilla screenshot proving that it only exists with Carbon)
http://imgur.com/nsZb1x1,EXrxgJA (screenshots from a Spigot server running Carbon with this behavior)

**Comment by k3ldon** [comment]
confirmed with build 42 and with build 40 works

**Comment by tnytown** [comment]
Slight amendment: it's the comparators' problem.

**Comment by tnytown** [comment]
Another amendment: The directions of the comparators and the item frames matter.

**Comment by Shevchik** [comment]
Probably has something to do with directions calculations, will fix it later.

**Comment by Shevchik** [comment]
Should be fixed now.
