### ISSUE TITLE
Villager Trading UI/AI

### ISSUE THREAD

**Issue by rlf** [NavidK0/Carbon#155]
The villager trading changes in 1.8 doesn't seem to be on either list of "completed" or "future" work for Carbon.

The full list seems to be availale on the wiki (http://minecraft.gamepedia.com/Villager), but the things I miss the most are:

Villagers only breed when willing. This limits the amount of villagers and prevents infinite breeding villages.

Farmer (profession) villagers now harvest fully grown crops, and can be forced to breed with 3 bread, or 12 carrots/12 potatoes.

And Trading rotten-flesh :) Finally a use for that crappy stuff.

**Comment by NavidK0** [comment]
Too many changes in AI to be worth doing when Spigot 1.8 is so close.

**Comment by rlf** [comment]
Got it - I can live without the "auto-iron-farm" being harder to obtain :D
