### ISSUE TITLE
"/worldborder help" doesn't work, plus own commands are shown on chat log

### ISSUE THREAD

**Issue by starg09** [NavidK0/Carbon#156]
That's basically it. Help doesn't work, and each time you use a command, the op logging message shows even if you sent the command yourself (not vanilla behaviour).

![2014-10-28_22 48 37](https://cloud.githubusercontent.com/assets/1235066/4820001/c211b1fa-5f0d-11e4-9b4b-ebda90b2b6d6.png)
![2014-10-28_22 48 13](https://cloud.githubusercontent.com/assets/1235066/4820003/c593ee24-5f0d-11e4-8d03-4ca45dfb195c.png)

**Comment by Matmorcat** [comment]
The /worldborder command does absolutely nothing for me. Not even a message that says "Unknown command." Just silence.

**Comment by starg09** [comment]
It should at least give you "commands.worldborder.usage",,,

I'm in 48 and it still works, although it still doesn't have help, and logs ownmade commands

**Comment by Matmorcat** [comment]
Updated to build 54. Still no response to any variation of /worldborder.

**Comment by Shevchik** [comment]
Then you are not op. If you are not op carbon just silently ignores the command.

**Comment by starg09** [comment]
That may be because of the natural behavior of the world border itself:
IIRC, the border has the same size on all dimensions, even in the nether
where the dimensions are 8 times smaller compared to overworld's (don't
exactly know what happens when you make a portal in an area supposed to be
outside the border, but that's another topic). Anyway, the point is that
functionality may not be compatible with multiverse-ish plugins, as all
worlds will more likely have the same border size...

EDIT: This was a response to a comment Matmorcat made, but doesn't appear to show here :/

**Comment by NavidK0** [comment]
Carbon is no longer supported for 1.8
