### ISSUE TITLE
Efficiency Enchant causes ghostblock to appear with packed ice

### ISSUE THREAD

**Issue by switorik** [NavidK0/Carbon#158]
When mining packed ice with silktouch + efficiency 1 or 2 yields packed ice, but with efficiency 3,4, or 5 it generates a ghost block (Disappears until you log out and re-appears when you log back in).

**Comment by Jikoo** [comment]
In 1.7 packed ice doesn't have a proper tool. You'll find similar results trying to chop melons with an axe. Just use anything else with silk touch.

**Comment by NavidK0** [comment]
I can't reproduce this issue. Could you post your plugins and check for errors in console?

**Comment by switorik** [comment]
I can only reproduce this error with a pickaxe. All other tools seem to work fine. As for plugins enabled, I have disabled all but carbon and the issue persists and there are no errors in the console.

Its not a big issue to me, but players are complaining because that is the only tool they have silk touch on.

**Comment by Jikoo** [comment]
This issue should actually be present without Carbon as well. Like I said before, in 1.7 packed ice doesn't have a proper tool. That means efficiency has no effect on it. In 1.8 a pick is the proper tool, resulting in client desync when the block breaks too fast.

**Comment by NavidK0** [comment]
This will require modification of packed ice. I will work on this soon.

**Comment by penturt** [comment]
has there been any progress on this issue?

**Comment by NavidK0** [comment]
It's more complicated than I originally thought. The server doesn't agree with the client on the tool being used.

**Comment by switorik** [comment]
This is just my input and take it as you see fit, the bug isn't that bad and I only put it here because I was recommended to when I posted on forums. I feel the time and effort to fix this can be better spent elsewhere.

**Comment by NavidK0** [comment]
Carbon is no longer supported for 1.8
