### ISSUE TITLE
Mob Spawner dont spawn Guardians not Elder Guardians

### ISSUE THREAD

**Issue by pr4xt3roy** [NavidK0/Carbon#159]
Hello,

I do not know if I am doing something wrong or if this is a known issue or just something that was not addressed yet.

I placed a mob spawner like so:

```
/setblock ~ ~ ~ minecraft:mob_spawner 0 false {EntityId:Guardian}
```

as stated in this issue: https://github.com/NavidK0/Carbon/issues/101

No guardian seem to spawn. I tried in water, in deep ocean, inside an ocean monument, nothing seem to work.  I am not in peaceful mode. Any advice?

Thanks.

**Comment by starg09** [comment]
Note: Just want to leave noted that Elder Guardians aren't supossed to spawn from a "Guardian" spawner. There are only 3 spawns in each monument, in specific rooms.

**Comment by NavidK0** [comment]
Mob spawners spawn any entity, this is not a Carbon issue.

**Comment by starg09** [comment]
I jus thought of something... You put the spawner with water around right? Because they won't spawn in mid air... Check any Guardian Farm on youtube and you'll see they need the 2x2 water pads for them to spawn.

**Comment by pr4xt3roy** [comment]
My bad, I wanted to say that Guardians dont spawn from Guardian Spawners and  ElderGuardians dont spawn from ElderGuardian Spawners.
Yes, I put the spawner in water in a DeepOcean biome and it was not spawning. there was more than 2x2 water around it. I will try the dev version of Carbon to see if it makes any difference.
Thank you

**Comment by pr4xt3roy** [comment]
In the new dev version (build 57), the regular and elder guardians are now spawning fine.
