### ISSUE TITLE
[Enhancement] 1.7 Mob Support

### ISSUE THREAD

**Issue by iamnessy2** [NavidK0/Carbon#161]
Is it possible that for the visual of 1.7 clients that you add a name tag over chicken, squid, and silverfish  if it's a 1.8 mob, unless it's actually that 1.7 mob.

Like this:
![image](https://cloud.githubusercontent.com/assets/2790585/4855983/4f0ffc76-60b0-11e4-9014-a564a8d502f9.png)

**Comment by Shevchik** [comment]
It is possible, but we won't do it.
