### ISSUE TITLE
with op works but without not...

### ISSUE THREAD

**Issue by k3ldon** [NavidK0/Carbon#162]
Well... i can use that items with op but if i put deop they do not work...
Any ideas?

Cooked Rabbit
Slime Block
Cooked_Mutton

Carbon v1.8
Server version git-Spigot-1.7.9-R0.2-207-g03373bb

**Comment by Shevchik** [comment]
NoCheatPlus doesn't support new mechanincs.
Learn to search.

**Comment by asofold** [comment]
Do you implement isEdible for the new food materials (Material class)?

NCP only accepts consumption of food (+potion + milk bucket) !

Edit: New ticket: https://github.com/NavidK0/Carbon/issues/167
