### ISSUE TITLE
Add a configuration to disable/enable individual mechanics, blocks, and items.

### ISSUE THREAD

**Issue by Matmorcat** [NavidK0/Carbon#163]
It would be nice if you could disable or enable parts of Carbon that you like for your server. This allows others to customize what they want to enable or disable from their server, because some of the features added conflict with plugins and other mechanics.

I don't mean blocking an item or block from being placed, but actually prevent it from being loaded as a block in the first place. It would also be nice to prevent mechanics such as placing buttons on the top/bottom of blocks and 45 degree rotations for item frames from taking effect.

**Comment by NavidK0** [comment]
Added.

**Comment by NavidK0** [comment]
As of commit: https://github.com/NavidK0/Carbon/commit/849ec0633ddff056a0b47f2054b9884a11d327e2
