### ISSUE TITLE
Players in teams set via /scoreboard do not have their team color in the TAB menu.

### ISSUE THREAD

**Issue by Matmorcat** [NavidK0/Carbon#164]
Say I do

```
/scoreboard teams join Blue Matmorcat
```

which adds me to a team which has the color option set to blue.

If another player who is online checks TAB, my name will remain white to them if they're on a 1.8 client.
If I relog, though, my name will appear the right color when I rejoin, but only to the online players, and only while they are online.

The same thing happened when I updated to Spigot 1.8 protocol hack, while I was using NameTags to edit TAB list colors, which lead to me using teams to color names on join. With Carbon, this problem has re-appeared for the vanilla teams system.

**Comment by NavidK0** [comment]
What does this have to do with Carbon? It seems like a general l spigot 1.8 issue, because Carbon doesn't even touch the scoreboard.

**Comment by Matmorcat** [comment]
The problem only occurs when you run the Carbon plugin. I've ran a server with over 20 people online, never had this issue. I made a clone of the server onto our beta server, the tablist still worked fine. Then we installed Carbon on the beta server, names appeared as described above.

It only happened when Carbon was installed.

**Comment by Matmorcat** [comment]
@NavidK0 You misunderstood me when I said "This problem has re-appeared." I was refering to the fact that there was a similar problem with NameTags, which I understand is unrelated.

Without Carbon (on 1.7 or 1.8 client), my server's tablist is full of colors (using teams to color names in Tab and Chat), but with Carbon (on 1.8 client), only players who join after you have colored names, the rest are white.

/scoreboard team colors only show properly on 1.7 clients while on 1.8 (with Carbon), they do not show for a client upon joining that client joining the server.

Spigot + Carbon (via a 1.8 client): https://www.dropbox.com/s/u6mzdatizlvwmir/2014-11-01_23.12.08.png?dl=0
Spigot + Carbon (via a 1.7 client): https://www.dropbox.com/s/nts2cnh4mi5mllh/2014-11-01_23.12.13.png?dl=0

I hope this helped clear up the confusion. I am 100% certain this is an issue that happens as a result of loading Carbon. We've been running fine for over a month without Carbon, where the Tab list is fully colored. No other plugins, configs, etc. were changed before this problem appeared.

**Comment by NavidK0** [comment]
My apologies. I'll look into this issue soon enough. I'm not at all sure why this would occur though.

**Comment by NavidK0** [comment]
I think this occurs because the data received for 1.8 clients for scoreboards is now different.

**Comment by Puremin0rez** [comment]
I can vouch for this. Carbon installed on a server will result in exactly this - messing up the beautiful tab list.

I wonder why this would be happening? IIRC Carbon doesn't touch anything scoreboard related.

**Comment by Matmorcat** [comment]
I updated to dev build 54 and it appears to be working again... Thanks if someone fixed it.

**Comment by Matmorcat** [comment]
It's still happening, never mind.

**Comment by NavidK0** [comment]
Carbon is no longer supported for 1.8
