### ISSUE TITLE
Storing and removing banners with patterns in block inventories results in an error.

### ISSUE THREAD

**Issue by Matmorcat** [NavidK0/Carbon#165]
Placing a banner with a pattern (for example a black banner with a blue box in the top right) in blocks such as chests and hoppers creates an error in console. Same thing happens for removing items from the inventories.

Latest Spigot Patch
Carbon change 43 (Jenkins)

Stack Trace:
https://gist.github.com/Matmorcat/f3bda14f16084f60b619

**Comment by Shevchik** [comment]
Forgot to override object stream method, will fix it soon.

**Comment by Shevchik** [comment]
CoreProtect does this instead of properly serializing itemstack so i will save it for later.
Not really sure that i should add a workaround for this.

**Comment by Matmorcat** [comment]
CoreProtect is a really common plugin. It's the 7th most used plugin on MCStats with more than 8,700 other servers using it. I'm sure there are plenty of others that will be bugged by the spam of errors in console. :frowning:

**Comment by Shevchik** [comment]
But it is not a Carbon error. It is a coreprotect that does shit. Coreprotect won't work in 1.8 unless updated. And i don't want to add object serializer because it increases the chance that we will have to provide Carbon api to support banner serialize/deserialize when normal spigot 1.8 releases.

**Comment by NavidK0** [comment]
CoreProtect needs to be updated for 1.8. Bother the plugin author about this, Spigot 1.8 is right around the corner.
