### ISSUE TITLE
Implement org.bukkit...Material instance methods.

### ISSUE THREAD

**Issue by asofold** [NavidK0/Carbon#167]
At last the new foods have isEdible return false, thus other plugins can't support the new materials properly.

Probably you can change the injection methods to add the new Material instances with a blueprint for selected methods, e.g. using an existing Material instance to just copy the methods results? (thinking of  at least isFlammable, isBurnable, isBlock, isSolid, isTransparent, isOccluding, isRecord, hasGravity - maybe getMaxStackSize and getMaxDurability too...)

Certainly not critical, but some plugins rely on some of those methods. (Edited to clarify.)

**Comment by NavidK0** [comment]
This is not easily done, modifying static enumerators is already tough as it is, you cannot modify the class structure directly in the JVM, it's not even possible with reinstrumentation.

**Comment by Shevchik** [comment]
But we can still reinstrument methods, so i think we can change this.
But the question is why the fuck bukkit directly compares with some materials istead of storing this in a variable inside the material >_<.

**Comment by asofold** [comment]
If it's getting too complicated, just do without it :p. Spigot will be on 1.8 some day and i could work around the isEdible with less complex methods for my own plugin(s), though some other peoples plugins might suffer with those methods not being up to date.

**Comment by NavidK0** [comment]
We always have the option to make Carbon a full mod where you have to open up the spigot jar and replace Material.class with our own with WinRAR. :P
