### ISSUE TITLE
LWC protections not working.

### ISSUE THREAD

**Issue by penturt** [NavidK0/Carbon#168]
Tho, Carbon is compatible with LWC , i'm having an odd issue when adding protections to any new 1.8 door.

I can set protections on the new doors without problem, yet any player can still open the door and walk through it. When they open the door It displays the "this block is protected..." message, but still opens for them. Using /cinfo confirms that the door is protected and private.

I have tried using item ids instead of thier bukkit names. But, that just resulted in players not able to protect any of those doors/blocks, seems like LWC doesn't register them as a lockable item/block. I have reverted back to using bukkit names.

Current core.yml: http://pastebin.com/vEqYM4nk

**Comment by NavidK0** [comment]
I'm not sure, but it seems like someone will have to update LWC for 1.8.

**Comment by RawrUniversal** [comment]
This might seems kinda late... but here: https://github.com/megoesrawr/LWC1.8

I updated it for the doors. ALSO, i got a version I MIGHT release for locking entities, like armor stands and item frames/paintings.

**Comment by NavidK0** [comment]
Carbon is no longer supported for 1.8
