### ISSUE TITLE
[BUG] Guardian does not drop correct items

### ISSUE THREAD

**Issue by pupnewfster** [NavidK0/Carbon#17]
Just putting this here for now later when I have time which may be tomorrow or today I am not sure yet I can work on this.

**Comment by NavidK0** [comment]
The new mobs are not ready for modification, all the code is placeholder

**Comment by mibby** [comment]
Ah, I was just about to create a ticket for this as well. :P Compiled source as of commit https://github.com/NavidK0/Carbon/commit/9a8af274f2dfcdf08e90643073ee505fdafea75e

**Comment by pupnewfster** [comment]
Changed title as rabbits now drop correct items.

**Comment by NavidK0** [comment]
Fixed
