### ISSUE TITLE
If i create a new Map with "Multiverse-Core" there will be no gold, diamond, coal in the grounds. Only Stones.

### ISSUE THREAD

**Issue by google90** [NavidK0/Carbon#170]
i have a problem with your Plugin "Carbon 1.7" till to the latest Versioncarbon.1258. I use Spigot 1.7 with 1.8 Spigot hack spigot-20141001a.md5

If i create a new Map with "Multiverse-Core" there will be no gold, diamond, coal in the grounds. Only Stones.
If it generates new chunks if a player is walling in the world, all of my worlds are generateing new chunks but without coal, diamonds, iron and lapislazuli. 

I have set the Worldname into the config. The Problem exists.

Maybe you can take a look. It will be awesome!

Thank you very much for you Plugin, and it will be great to hear from you.

Best regards

**Comment by NavidK0** [comment]
Do you have dynmap? Dynmap is not compatible. You need to prerender your world without dynmap first, and then add dynmap back if you have it.

The world name is case sensitive in the config. You also need to add the world name BEFORE you generate the world in the config.

**Comment by google90** [comment]
Yes i have running a Dynmap. I have remove the Dynmap Plugin and all runs perfekt.

THank you for you help!
