### ISSUE TITLE
Carbon spawning too many mobs?

### ISSUE THREAD

**Issue by sirbrando** [NavidK0/Carbon#172]
Hello, I have mobs normally limited on my server, so not too many spawn. When I updated carbon to build #47 a lot more mobs are spawning, and causing strain on my server. Did something change? I know guardians was one thing, are they going past the mob limit? Also I tried disabling all mob spawning in the carbon config and there's still too many mobs spawning.

**Comment by NavidK0** [comment]
Carbon doesn't touch other mobs, it only adds new ones. This shouldn't change the mob count... and I can't reproduce this issue. What plugins do you have, and do you have any logs?

**Comment by Shevchik** [comment]
There was a change to  SpawnerCreature which controls the spawning. I half copied it from 1.8, so this probably increased mob spawning.

**Comment by Shevchik** [comment]
Indeed there is a change in how mob spawning in 1.8 works, so you will have to lower your spawn limits.

**Comment by mibby** [comment]
I can confirm that guardian spawns are a bit crazy. As far as I've seen, only guardians. 200 guardians in 2 minutes. :(
