### ISSUE TITLE
Worldgen is on by default in every world

### ISSUE THREAD

**Issue by starg09** [NavidK0/Carbon#173]
I updated to Build #48, and since then our void world, where my friends and I have been mapping, started generating terrain... I've tested in several types of void worlds (besides the one we had downloaded long ago from internet, we generated one with a plugin, and a customized superflat made by hand...), and in all the "voidness" generates perfectly without carbon, but as soon as you enable the plugin, new chunks generate with the injected generator (I notice because of the new stones). Could you please try to fix this? It's a pretty annoying bug D:

**Comment by NavidK0** [comment]
Nothing has changed with world generation, this is most likely an issue on your end. Erase Carbon's config and check, world generation is NOT on by default in every world, and it's a whitelist, so the name of the world has to be on in the config in order for it to even work.

**Comment by Shevchik** [comment]
Carbon injects its own ChunkProviderGenerate to enable generation of monuments, i will make it respect worlds config option later.

**Comment by starg09** [comment]
Ok, I'll wait a bit to update then... Thanks for replying :)

**Comment by starg09** [comment]
~~Welp, last build fixed this in some way... Worldgen is off by default now, but no matter how much I try I can't get new worldgen to work on a world/server (It justs uses default gen, veen if in whitelist)~~

~~I prefer not being able to generate than being forced to, though xD~~

~~Anyway, I'll change the title to update to the current situation :P~~

---

~~tl;dr: You want worldgen, use Build 57 (Will generate in all worlds, even void ones). You don't want worldgen, use Build 58 (Won't generate anything at all in any world).~~ Not related with this issue, see #177

**Comment by starg09** [comment]
Closed the issue because it's fixed, there's another bug, but I'll report it in a new issue (Again, sorry for the comment spam)
