### ISSUE TITLE
Any possibility in bringing back the banner sway fix for old worlds?

### ISSUE THREAD

**Issue by mibby** [NavidK0/Carbon#174]
I have a very large 40,000 x 40,000 pre-generated 1.7 world for my server. Some users are complaining that banners aren't swaying. I believe I read in one of the earlier commits that this is a vanilla minecraft bug with old worlds not supporting it. However, I remember a carbon commit that was a workaround for the issue, allowing banners to sway on old worlds.

I was wondering if it was possible to bring back the workaround fix, or rewrite the fix to be bug free.

**Comment by Shevchik** [comment]
No. Swaying is based on coords, not only world time, so fully fixing it is impossible server side.
