### ISSUE TITLE
Carbon WorldGen not working properly in spawn chunks

### ISSUE THREAD

**Issue by starg09** [NavidK0/Carbon#177]
~~This happens when you have a single world, and enable it in Carbon's config:~~

~~\* If you set a seed in the server.properties, even if the world is whitelisted by Carbon's generator, world will generate as 1.7~~
~~\* If you don't set a seed, Carbon will work perfectly, but will choose a random seed.~~

~~So, I think the solution would be adding a seed option in the config, maybe? That or making it take the seed value in the server.properties~~

**EDIT:** The bug is actually about worldgen at spawn chunks. Look down for more info.

**Comment by Shevchik** [comment]
Carbon takes the seed from the world, so it should still work.
It works in my case, i taken some random seed from the internet and it worked.
Probably you have some other plugin that controls seed (Any multiworld plugin does that)

**Comment by starg09** [comment]
I'll make a check on this, if I find a plugin that affects it I will put it down here and close the issue.

**Comment by starg09** [comment]
Welp, I think this must be the weirdest bug I've ever seen in my 3 years working with bukkit/spigot. It seems to generate 1.7 terrain up to ~180 block around spawn. Outside this area new stones start to generate, so it seems to be some issue in that area... If I regenerate the are with worldedit, the new stones appear...

My guess would be some issue with the worldgen injection when it comes to the "spawn chunks", as the affected region is pretty similar in size to them.

**Comment by starg09** [comment]
I also notice maybe the amount of new stones generated is a bit low, but I could be wrong (84k of all three types out of 2 million stone seems a bit short to me :P )

PS: I tested this with only Carbon, and later with only Carbon and WorldEdit. Same result, so it's a Carbon bug...

**Comment by starg09** [comment]
Checked a little more... I found a way to make these spawn chunks generate Carbon terrain, although the process is a bit tedious...
- First, you must note down the coords of where you spawned (for reference)
- Then, you must go to a really far away area (like -9000 100 -9000), and use "/setworldspawn"
- Don't go back to the first area yet. You must stop the server, and remove all region files corresponding to that area (Erasing "-1,-1" to "1,1" will most likely delete the area you're looking for, but will remove quite a lot of chunks, a backup is recommended in case there are structures near spawn)
- Restart the server, and tp back to the original coords. You can use setworldspawn again, and if you check with worldedit, the chunks will now have generated with the new stones.

Although this could be a potential solution, it's highly impractical. I hope you can find a solution to this soon :)

**Comment by NavidK0** [comment]
Carbon is no longer supported for 1.8
