### ISSUE TITLE
[issue] Internal exception: java.lang.NullPointerException 

### ISSUE THREAD

**Issue by Mihajlo123** [NavidK0/Carbon#178]
http://i.imgur.com/GZ4SjEG.png?1
May anyone know what the problem is?
I'm using the latest spigot version, carbon 1.7 (cofigured well...).
After a few minutes being up, the server crashes...
This is what my console says:
http://i.imgur.com/xeQSMxu.png?1
http://i.imgur.com/8ybC7MJ.png?1

**Comment by Matmorcat** [comment]
Did you update WorldGuard? If I had to guess, it looks like there's some conflict between RandomLocation and the version of WorldGuard you're using.

**Comment by starg09** [comment]
@Matmorcat Seems more like a RandomLocation conflict with Worldguard rather than with WorldEdit, although in any case it has nothing to do with this plugin :)

**Comment by Shevchik** [comment]
LEARN TO READ!
