### ISSUE TITLE
Make Enderman attack endermites

### ISSUE THREAD

**Issue by starg09** [NavidK0/Carbon#179]
In 1.8, Enderman attack Endermites, and won't stop until it kills them. It starts once it's field of view detects an Endermite entity. In a more precise way, they will only attack Endermites which spawn after a player uses Ender pearls (those have an special NBT tag).

I don't quite remember if they still spawn when an Enderman teleports, but if they do, those shouldn't be attacked. Obviously, it's easier to make Endeman attack all Endermites, it's not like it will make that big of a difference... Well, it will make fighting in the end a bit more difficult :P

**Comment by NavidK0** [comment]
Carbon is no longer supported for 1.8

Keeping this here as it's a bug that needs to be fixed for this version of Carbon, if it ever does get fixed before Carbon 1.9 is created.
