### ISSUE TITLE
Mobs remove armor stand entity and pick up items when passing through.

### ISSUE THREAD

**Issue by mibby** [NavidK0/Carbon#180]
It seems mobs can interact / remove armor stands. A zombie walked into an armor stand full of armor, removed/delete the entity, and automatically picked up wearing the armor and item held that was on the stand. Is it natural for zombies to remove armor stand entities when passing through? Killing the zombie dropped the armor, the armor stand, and the item held.

**Comment by Shevchik** [comment]
Armor stand can collide with other entities.

**Comment by mibby** [comment]
Right, but should the armor stand itself be absorbed when a zombie walks through it? The items on the armor stand get put on the zombie and the armor stand itself disappears. Killing the mob drops the armor stand and the items.

**Comment by Shevchik** [comment]
Don't know, never tested this on vanilla.

**Comment by NavidK0** [comment]
Carbon is no longer supported for 1.8

Keeping this here as it's critical, but it will be removed when/if Carbon 1.9 is created.
