### ISSUE TITLE
Players can destroy armour stands in private.

### ISSUE THREAD

**Issue by Leymooo** [NavidK0/Carbon#185]
Players can destroy armour stands in private.
How fix it?

Как это пофиксить? 
Я спавн делаю в стиле 15 века,думал в замке стоек наставить и на рынке возле продавцов НПС.
А это ни как не сделать( Помоги плз. Стойки ломаются в привате игроками у которых нет прав на регион(

**Comment by Jikoo** [comment]
Your protection plugin needs to update to handle this. Carbon has done its part by firing an EntityDamageByEntityEvent when armor stands are destroyed.

**Comment by Leymooo** [comment]
Last WG dev build not support this( Where i can found this plugin?

Слушай. Последний WG дев билд не поддерживает это. Как быть?

**Comment by Shevchik** [comment]
Write your own.

**Comment by Leymooo** [comment]
Я не умею(

**Comment by Leymooo** [comment]
Можешь ты это добавить в WGExtender?

**Comment by NavidK0** [comment]
No, it's not our business to modify add "extensions" to support other plugins that are not ready for 1.8. Why? Because plugins that need an extension will also break when Spigot 1.8 is released.
