### ISSUE TITLE
When I generate a new world with carbon, then I have no ores up to Emerald

### ISSUE THREAD

**Issue by Sneeper89** [NavidK0/Carbon#187]
I have absolutly no Ores up to Emerald, You can look wenn you go deaper and make a hole with WorldEdit. And you make "//replace 1 0"  you will see there no Ores, PLS do not make "//Set 0" make "//replace 1 0" !

Thx
Sneeper89

**Comment by Shevchik** [comment]
Uninstall dynmap.

**Comment by unicxa** [comment]
@shevchik can we possibly find away around this by implementing the dynamic plugin I'm not 100% sure if we can coad around this, anyway I was going to give it a try. I believe something might be overriding the the set block command and thus dynamic map looks at it as a unidentified block so errors occur we could make a modified dynamic map with permission from the lead developer of dynamic map

**Comment by unicxa** [comment]
Oh btw I have been afk on this project bc im working on a 2D java platformer for a contest I would help more but I'm extremely busy I'm also studding for my CompTIA exam

**Comment by unicxa** [comment]
Wish me luck :-)
