### ISSUE TITLE
Server version number change when using Carbon

### ISSUE THREAD

**Issue by vbisbest** [NavidK0/Carbon#190]
Hello, I am the developer of MineChat.  I have an issue connecting to servers using Carbon.  The problem is that the server ping request says the the server is protocol 5 (MC 1.7.9).  MineChat then attempts to connect to the server with the same protocol and then gets disconnected because carbon is requiring protocol 47 for MC 1.8.   It would be helpful if Carbon could change the ping response to say the correct server version.  Would like to hear your thoughts on this.  Thank you for your help.

Ray

**Comment by Shevchik** [comment]
Will do it soon.

**Comment by vbisbest** [comment]
Thank you so much.  That will help with a LOT of our users.
