### ISSUE TITLE
Format to add world to config

### ISSUE THREAD

**Issue by xmcnuggsx** [NavidK0/Carbon#191]
What is the proper format to add a world into the carbon config file? I have tried it several ways and still cannot manage to generate a world with 1.8 blocks. I will troubleshoot conflicting plug-ins once I know I have the config set up properly. Everything else other than the world-gen is working great for me. Thanks.

**Comment by Shevchik** [comment]
It is a YAML list.

**Comment by Jikoo** [comment]
YAML lists are formatted `list: [item, item, item]` or

``` yaml
list:
- item
- item
- item
```

Either will work.

**Comment by xmcnuggsx** [comment]
Great, thanks guys!
