### ISSUE TITLE
NavidK0 told me to post this up !

### ISSUE THREAD

**Issue by bros1083** [NavidK0/Carbon#192]
I went on IRC it says it interesting 
---- Minecraft Crash Report ----
// Don't do that.

Time: 10/16/14 8:46 PM
Description: Loading NBT data

java.util.zip.ZipException: incorrect data check
    at java.util.zip.InflaterInputStream.read(Unknown Source)
    at java.io.BufferedInputStream.fill(Unknown Source)
    at java.io.BufferedInputStream.read1(Unknown Source)
    at java.io.BufferedInputStream.read(Unknown Source)
    at java.io.DataInputStream.readFully(Unknown Source)
    at java.io.DataInputStream.readFully(Unknown Source)
    at net.minecraft.server.v1_7_R4.NBTTagByteArray.load(NBTTagByteArray.java:29)
    at net.minecraft.server.v1_7_R4.NBTTagCompound.a(SourceFile:329)
    at net.minecraft.server.v1_7_R4.NBTTagCompound.load(SourceFile:41)
    at net.minecraft.server.v1_7_R4.NBTTagList.load(SourceFile:37)
    at net.minecraft.server.v1_7_R4.NBTTagCompound.a(SourceFile:329)
    at net.minecraft.server.v1_7_R4.NBTTagCompound.load(SourceFile:41)
    at net.minecraft.server.v1_7_R4.NBTTagCompound.a(SourceFile:329)
    at net.minecraft.server.v1_7_R4.NBTTagCompound.load(SourceFile:41)
    at net.minecraft.server.v1_7_R4.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:119)
    at net.minecraft.server.v1_7_R4.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:84)
    at net.minecraft.server.v1_7_R4.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:79)
    at net.minecraft.server.v1_7_R4.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:82)
    at org.bukkit.craftbukkit.v1_7_R4.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:19)
    at org.bukkit.craftbukkit.v1_7_R4.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:13)
    at org.bukkit.craftbukkit.v1_7_R4.util.AsynchronousExecutor$Task.init(AsynchronousExecutor.java:150)
    at org.bukkit.craftbukkit.v1_7_R4.util.AsynchronousExecutor$Task.initAsync(AsynchronousExecutor.java:95)
    at org.bukkit.craftbukkit.v1_7_R4.util.AsynchronousExecutor$Task.run(AsynchronousExecutor.java:85)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at java.util.zip.InflaterInputStream.read(Unknown Source)
    at java.io.BufferedInputStream.fill(Unknown Source)
    at java.io.BufferedInputStream.read1(Unknown Source)
    at java.io.BufferedInputStream.read(Unknown Source)
    at java.io.DataInputStream.readFully(Unknown Source)
    at java.io.DataInputStream.readFully(Unknown Source)
    at net.minecraft.server.v1_7_R4.NBTTagByteArray.load(NBTTagByteArray.java:29)

-- NBT Tag --
Details:
    Tag name: SkyLight
    Tag type: 7
Stacktrace:
    at net.minecraft.server.v1_7_R4.NBTTagCompound.a(SourceFile:329)
    at net.minecraft.server.v1_7_R4.NBTTagCompound.load(SourceFile:41)
    at net.minecraft.server.v1_7_R4.NBTTagList.load(SourceFile:37)
    at net.minecraft.server.v1_7_R4.NBTTagCompound.a(SourceFile:329)
    at net.minecraft.server.v1_7_R4.NBTTagCompound.load(SourceFile:41)
    at net.minecraft.server.v1_7_R4.NBTTagCompound.a(SourceFile:329)
    at net.minecraft.server.v1_7_R4.NBTTagCompound.load(SourceFile:41)
    at net.minecraft.server.v1_7_R4.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:119)
    at net.minecraft.server.v1_7_R4.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:84)
    at net.minecraft.server.v1_7_R4.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:79)
    at net.minecraft.server.v1_7_R4.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:82)
    at org.bukkit.craftbukkit.v1_7_R4.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:19)
    at org.bukkit.craftbukkit.v1_7_R4.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:13)
    at org.bukkit.craftbukkit.v1_7_R4.util.AsynchronousExecutor$Task.init(AsynchronousExecutor.java:150)
    at org.bukkit.craftbukkit.v1_7_R4.util.AsynchronousExecutor$Task.initAsync(AsynchronousExecutor.java:95)
    at org.bukkit.craftbukkit.v1_7_R4.util.AsynchronousExecutor$Task.run(AsynchronousExecutor.java:85)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Linux (amd64) version 2.6.32-431.11.2.el6.x86_64
    Java Version: 1.7.0_55, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 205636160 bytes (196 MB) / 518979584 bytes (494 MB) up to 518979584 bytes (494 MB)
    JVM Flags: 5 total; -Xmx512M -Xms512M -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    CraftBukkit Information: 
   Running: CraftBukkit version git-Spigot-1649 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT) true
   Plugins: { GroupManager v2.1.30 (Phoenix) org.anjocaido.groupmanager.GroupManager [AnjoCaido, Gabriel Couto, ElgarL], WorldEdit v5.6.3 com.sk89q.worldedit.bukkit.WorldEditPlugin [], AutoBroadcaster v0.4 me.skipperguy12.autobroadcasterplus.AutoBroadcasterPlus [], MassiveCore v7.4.0 com.massivecraft.massivecore.MassiveCore [Cayorion], iDisguise v3.1pre3 de.robingrether.idisguise.iDisguise [Robingrether], ClearLag v2.7.2 me.minebuilders.clearlag.Clearlag [bob7l], Multiverse-Core v2.5-b691 com.onarandombox.MultiverseCore.MultiverseCore [Rigby, fernferret, lithium3141, main--], ProtocolLib v3.4.0 com.comphenix.protocol.ProtocolLibrary [Comphenix], mcMMO v1.5.00-b3547 com.gmail.nossr50.mcMMO [nossr50, GJ, NuclearW, bm01, Glitchfinder, TfT_02, t00thpick1, Riking], WorldGuard v6.0.0-beta-02 com.sk89q.worldguard.bukkit.WorldGuardPlugin [], ClearChat v4.8 com.squareboxmedia.clearchat.ClearChat [Charles], Essentials v2.13.1 com.earth2me.essentials.Essentials [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally], SilkSpawners v3.5.1 de.dustplanet.silkspawners.SilkSpawners [xGhOsTkiLLeRx, mushroomhostage], EssentialsProtect v2.13.1 com.earth2me.essentials.protect.EssentialsProtect [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits], NoCheatPlus v3.11.1-RC-sMD5NET-b743 fr.neatmonster.nocheatplus.NoCheatPlus [NeatMonster, asofold, Evenprime], EssentialsSpawn v2.13.1 com.earth2me.essentials.spawn.EssentialsSpawn [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits], Multiverse-Portals v2.5-b699 com.onarandombox.MultiversePortals.MultiversePortals [Rigby, fernferret], EssentialsChat v2.13.1 com.earth2me.essentials.chat.EssentialsChat [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Okamosy, Iaccidentally], EnjinMinecraftPlugin v2.6.8 com.enjin.officialplugin.EnjinMinecraftPlugin [www.Enjin.com], Factions v2.6.0 com.massivecraft.factions.Factions [Cayorion, Brettflan], ObsidianDestroyer v4.3.0 com.drtshock.obsidiandestroyer.ObsidianDestroyer [drtshock, squidicuz],}
   Warnings: DEFAULT
   Threads: { RUNNABLE Netty IO #0: [sun.nio.ch.EPollArrayWrapper.epollWait(Native Method), sun.nio.ch.EPollArrayWrapper.poll(Unknown Source), sun.nio.ch.EPollSelectorImpl.doSelect(Unknown Source), sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), net.minecraft.util.io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:591), net.minecraft.util.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:301), net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101), java.lang.Thread.run(Unknown Source)], TIMED_WAITING pool-28-thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source), java.util.concurrent.LinkedBlockingDeque.pollFirst(Unknown Source), java.util.concurrent.LinkedBlockingDeque.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Spigot Metrics Thread: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], RUNNABLE Server console handler: [java.io.FileInputStream.readBytes(Native Method), java.io.FileInputStream.read(Unknown Source), java.io.BufferedInputStream.fill(Unknown Source), java.io.BufferedInputStream.read(Unknown Source), java.io.FilterInputStream.read(Unknown Source), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader$1.read(ConsoleReader.java:167), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:267), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:204), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readCharacter(ConsoleReader.java:995), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLineSimple(ConsoleReader.java:1506), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:1153), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:1117), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:1105), net.minecraft.server.v1_7_R4.ThreadCommandReader.run(ThreadCommandReader.java:34)], TIMED_WAITING Timer-0: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], TIMED_WAITING Craft Scheduler Thread - 5: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Craft Scheduler Thread - 8: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING pool-6-thread-3: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING pool-19-thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source), java.util.concurrent.LinkedBlockingDeque.pollFirst(Unknown Source), java.util.concurrent.LinkedBlockingDeque.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING Java2D Disposer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.ReferenceQueue.remove(Unknown Source), sun.java2d.Disposer.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Craft Scheduler Thread - 3: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE Chunk I/O Executor Thread-1: [java.lang.Thread.dumpThreads(Native Method), java.lang.Thread.getAllStackTraces(Unknown Source), org.bukkit.craftbukkit.v1_7_R4.CraftCrashReport.call(CraftCrashReport.java:28), net.minecraft.server.v1_7_R4.CrashReportSystemDetails.a(SourceFile:74), net.minecraft.server.v1_7_R4.CrashReport.h(CrashReport.java:45), net.minecraft.server.v1_7_R4.CrashReport.<init>(CrashReport.java:33), net.minecraft.server.v1_7_R4.CrashReport.a(CrashReport.java:230), net.minecraft.server.v1_7_R4.NBTTagCompound.a(SourceFile:331), net.minecraft.server.v1_7_R4.NBTTagCompound.load(SourceFile:41), net.minecraft.server.v1_7_R4.NBTTagList.load(SourceFile:37), net.minecraft.server.v1_7_R4.NBTTagCompound.a(SourceFile:329), net.minecraft.server.v1_7_R4.NBTTagCompound.load(SourceFile:41), net.minecraft.server.v1_7_R4.NBTTagCompound.a(SourceFile:329), net.minecraft.server.v1_7_R4.NBTTagCompound.load(SourceFile:41), net.minecraft.server.v1_7_R4.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:119), net.minecraft.server.v1_7_R4.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:84), net.minecraft.server.v1_7_R4.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:79), net.minecraft.server.v1_7_R4.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:82), org.bukkit.craftbukkit.v1_7_R4.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:19), org.bukkit.craftbukkit.v1_7_R4.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:13), org.bukkit.craftbukkit.v1_7_R4.util.AsynchronousExecutor$Task.init(AsynchronousExecutor.java:150), org.bukkit.craftbukkit.v1_7_R4.util.AsynchronousExecutor$Task.initAsync(AsynchronousExecutor.java:95), org.bukkit.craftbukkit.v1_7_R4.util.AsynchronousExecutor$Task.run(AsynchronousExecutor.java:85), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Server Infinisleeper: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_7_R4.ThreadSleepForever.run(SourceFile:63)], TIMED_WAITING Craft Scheduler Thread - 2: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Snooper Timer: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], RUNNABLE DestroyJavaVM: [], TIMED_WAITING Craft Scheduler Thread - 0: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING MStore ExamineThread: [java.lang.Thread.sleep(Native Method), com.massivecraft.massivecore.store.ExamineThread.run(ExamineThread.java:55)], WAITING Thread-5: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), net.minecraft.util.com.mojang.util.QueueLogAppender.getNextLogEvent(QueueLogAppender.java:73), org.bukkit.craftbukkit.v1_7_R4.util.TerminalConsoleWriterThread.run(TerminalConsoleWriterThread.java:25), java.lang.Thread.run(Unknown Source)], TIMED_WAITING pool-16-thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source), java.util.concurrent.LinkedBlockingDeque.pollFirst(Unknown Source), java.util.concurrent.LinkedBlockingDeque.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING pool-6-thread-2: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE Server thread: [java.util.HashMap.resize(Unknown Source), java.util.HashMap.addEntry(Unknown Source), java.util.HashMap.put(Unknown Source), java.util.HashSet.add(Unknown Source), org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:170), org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:207), org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:207), org.yaml.snakeyaml.serializer.Serializer.serialize(Serializer.java:112), org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:272), org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:262), org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:234), org.yaml.snakeyaml.Yaml.dump(Yaml.java:209), org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:40), com.earth2me.essentials.EssentialsConf.delayedSave(EssentialsConf.java:303), com.earth2me.essentials.EssentialsConf.save(EssentialsConf.java:272), com.earth2me.essentials.EssentialsConf.save(EssentialsConf.java:256), com.earth2me.essentials.UserData.trackUUID(UserData.java:879), com.earth2me.essentials.EssentialsPlayerListener$2.run(EssentialsPlayerListener.java:233), org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71), org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350), net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:641), net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289), net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584), net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490), net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)], RUNNABLE Signal Dispatcher: [], WAITING Finalizer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)], TIMED_WAITING pool-22-thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source), java.util.concurrent.LinkedBlockingDeque.pollFirst(Unknown Source), java.util.concurrent.LinkedBlockingDeque.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Keep-Alive-Timer: [java.lang.Thread.sleep(Native Method), sun.net.www.http.KeepAliveCache.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING Reference Handler: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:503), java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)], TIMED_WAITING process reaper: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING pool-11-thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING pool-25-thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source), java.util.concurrent.LinkedBlockingDeque.pollFirst(Unknown Source), java.util.concurrent.LinkedBlockingDeque.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING pool-6-thread-4: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Craft Scheduler Thread - 1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING pool-6-thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Spigot Watchdog Thread: [java.lang.Thread.sleep(Native Method), org.spigotmc.WatchdogThread.run(WatchdogThread.java:92)], RUNNABLE Netty IO #1: [sun.nio.ch.EPollArrayWrapper.epollWait(Native Method), sun.nio.ch.EPollArrayWrapper.poll(Unknown Source), sun.nio.ch.EPollSelectorImpl.doSelect(Unknown Source), sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), net.minecraft.util.io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:591), net.minecraft.util.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:301), net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Craft Scheduler Thread - 4: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Craft Scheduler Thread - 6: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Craft Scheduler Thread - 7: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING File IO Thread: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_7_R4.FileIOThread.b(SourceFile:44), net.minecraft.server.v1_7_R4.FileIOThread.run(SourceFile:23), java.lang.Thread.run(Unknown Source)],}
   Recent tasks from 661-691{EnjinMinecraftPlugin:com.enjin.officialplugin.tpsmeter.MonitorTPS@709,Essentials:com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener$1@720,Essentials:com.earth2me.essentials.EssentialsPlayerListener$1@720,}
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 12; [EntityPlayer['FireNick1'/177, l='world', x=829.70, y=219.11, z=-42.30](FireNick1 at 829.6999999880791,219.11163302697386,-42.30000001192073)]
    Is Modded: Definitely; Server brand changed to 'Spigot'
    Type: Dedicated Server (map_server.txt)

**Comment by Shevchik** [comment]
Your world is corrupted. Run region fixer on it.

**Comment by bros1083** [comment]
So can I make a new world will that work

**Comment by bros1083** [comment]
Ok
Um.. What happens is I deleted EVERY world I had and then I added carbon. It did the injections and registered but at one point it says Failed at 1.8 injection. The funny part no crash report was made but it said the server crashed. BTW im using a host

**Comment by bros1083** [comment]
Mcprohosting

**Comment by Shevchik** [comment]
Post new crash reportj

**Comment by bros1083** [comment]
It does not make one

**Comment by bros1083** [comment]
Heres a picture of console remember I just press start
![image](https://cloud.githubusercontent.com/assets/9767598/5096979/63435d38-6f3c-11e4-90b2-5c8833e612b8.png)
