### ISSUE TITLE
ERROR Attempted to append to non-started appender Terminal Console

### ISSUE THREAD

**Issue by sidboy55555** [NavidK0/Carbon#194]
When i start the server the server automatic stops and this error is in the end of line when the server is stoped and says click an key to close

ERROR Attempted to append to non-started appender Terminal Console

whole log  http://pastebin.com/7rsmVGHd

**Comment by Shevchik** [comment]
GTFO.

**Comment by sidboy55555** [comment]
wtf? this is happening because barbon.... when i disable that plugin there is no error but when i enebled it there is this!

**Comment by Shevchik** [comment]
Because you didn't read the plugin page.

**Comment by sidboy55555** [comment]
i have readed everthing so please just say whats the problem?

EDIT: i think everthing :p

**Comment by Shevchik** [comment]
You are not using latest spigot version.

**Comment by sidboy55555** [comment]
i'm using spigot1649 if that is not the latest what is?

**Comment by Shevchik** [comment]
You even failed to read spigot wiki and news. Don't want to help you.

**Comment by sidboy55555** [comment]
thank you now i have it :D
ow and thank you for negative helping -_-

**Comment by NavidK0** [comment]
He's already multiple times that he would give that response to people who can't read. It's a waste of time helping those that cannot bother to read the documentation.
