### ISSUE TITLE
Can infinitely enchantment to one item (Bug)

### ISSUE THREAD

**Issue by BlackYamato** [NavidK0/Carbon#195]
It is possible to put an enchantment to infinity to one item by enchantment table.
Please as soon as possible fix.

Environment:
　・Spigot 1.7.9-R0.2-208-ge0f2e95 (MC: 1.7.10)
　　　Spigot build1649 Patched spigot-20141113a.bps.
　・Carbon 1.7 & build76

**Comment by Jikoo** [comment]
Your explanation is lacking and your meaning unclear. Could you explain the problem better and actually provide steps to replicate it?

**Comment by BlackYamato** [comment]
Result of the verification, it occurs when I introduce a EnchantPlus Plugin.
Carbon Plugin just does not occur.
I'm sorry.
