### ISSUE TITLE
not stacked items with carbon

### ISSUE THREAD

**Issue by k3ldon** [NavidK0/Carbon#198]
i have 2 worlds, one with carbon and in this world the items not get stack look the pic

http://ft.trillian.im/12c2f4a299b2175c0cef5646ecdfd3b38d452a84/6ulGoDd81FyqMDRIA4kTLYO4gEgeW.png

**Comment by NavidK0** [comment]
I see don't see any issue here...?

**Comment by k3ldon** [comment]
do not have any stacks of 64 with carbon, like in the picture

**Comment by NavidK0** [comment]
I do not believe this is a Carbon issue,  it's likely another plugin.

**Comment by NavidK0** [comment]
Carbon is no longer supported for 1.8
