### ISSUE TITLE
Lilypad Support

### ISSUE THREAD

**Issue by rocky143** [NavidK0/Carbon#199]
Hello all, 

I have been scratching my head over this issue but Carbon does not seem to work with lilypad.
I have tried emptying the protocolblocker.yml, I have tried installing protocollib but it give me this message on the server console where I am trying to connect to:
net.minecraft.util.com.mojang.authlib.GameProfile@7c59b580[id=<null>,name=Rocky143,properties={},legacy=false](/55.65.95.356:63592) lost connection: Disconnected

The only way Carbon could work with lilypad as of now is of you turn the option "online-mode" off in server.properties which is a requirement for lilypad that it has to say in online mode + other plugins that uses UUID breaks as well in offline mode. Lilypad is not like bungee where all the connected servers have to be in offline mode.

Any help will be appreciated!

**Comment by NavidK0** [comment]
Probably not going to happen anymore, Carbon is no longer supported for 1.8.
