### ISSUE TITLE
[Bug] Carbon 1.5 - Sea Lanterns do not keep light levels.

### ISSUE THREAD

**Issue by mibby** [NavidK0/Carbon#2]
Spigot with patch 20140927a.
Carbon version 1.5.

Placing down a sea lantern for the first time has the correct light levels and lights up the area. But, if you teleport away (unloading the chunk) and teleport back, that sea lantern is no longer lit.

**Comment by Shevchik** [comment]
Looks like light level is handled in the world itself. I will try to found a workaround.

**Comment by NavidK0** [comment]
We can possibly reload the sea lanterns on chunk load.

**Comment by Shevchik** [comment]
That won't help. This bug happens because placing sea lantern doesn't set light levels in a chunk.
I will try to set block light level on block place, but not sure if it will help.

**Comment by mibby** [comment]
Sea lanterns light levels confirmed fixed per this commit.
https://github.com/NavidK0/Carbon/commit/dd3a2fddbac85bf4cbf92bda9c9d22872bbd3153
