### ISSUE TITLE
Crash on jumping on slime blocks.

### ISSUE THREAD

**Issue by ghost** [NavidK0/Carbon#200]
My server shutdown giving me this error: http://pastebin.com/CSxkWY6i
I am using the latest spigot patch and have late-bind disabled in my spigot.yml.

What I did is I spawned a slime block. Jumped on it. Then in the middle of bouncing I flew up and the server crashed. I did it multiple times and it does the same thing.

I have Carbon, ProtocolBlocker-1.0.1, and ProtocolLib-Spigot-3.6.0-SNAPSHOT

**Comment by ghost** [comment]
Why was this closed??

**Comment by noidexe** [comment]
Probably because http://itsalmo.st/#spigot-18

**Comment by Shevchik** [comment]
No, that was closed because yoi didn't read the plugin page.
