### ISSUE TITLE
[Bug] Spawning in rabbits via mob egg also spawn in baby chicken.

### ISSUE THREAD

**Issue by mibby** [NavidK0/Carbon#22]
Right clicking the rabbit monster egg to spawn in rabbits, if I do not move the mouse around, it begins to spawn in chickens instead of rabbits.

![link](http://i.imgur.com/9XmZhSm.png)

**Comment by mcmonkey4eva** [comment]
The current rabbit seems to literally just be a chicken reskinned -> https://github.com/NavidK0/Carbon/blob/master/src/main/java/com/lastabyss/carbon/entity/EntityRabbit.java

**Comment by NavidK0** [comment]
Yep, I'm not working on it until I finish guardians.
In the meantime, rabbits extend the chickens class.

**Comment by bennasar99** [comment]
rabbits should be pigs reskinned maybe, if posible.
Pigs use carrots for breeding, like rabbits.

**Comment by NavidK0** [comment]
Fixed. Rabbits have their own AI now.
