### ISSUE TITLE
[BUG] 1.7 Crashes

### ISSUE THREAD

**Issue by ghost** [NavidK0/Carbon#31]
[USER=5652]@Aust1n46[/USER] erm, in 1.7 when I open my inventory in creative mode it disconnects me with:

http://i.gyazo.com/e06b19217c8dd8b43423bbbbadc06e66.png

and in survival I crash with:
[CODE]---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 05/10/14 14:48
Description: Rendering item

java.lang.NullPointerException: Rendering item
    at adc.c(SourceFile:99)
    at bqk.a(SourceFile:285)
    at bqk.b(SourceFile:400)
    at beu.a(SourceFile:240)
    at beu.a(SourceFile:105)
    at bfl.a(SourceFile:30)
    at bfr.a(SourceFile:47)
    at bof.b(SourceFile:852)
    at ban.ak(SourceFile:801)
    at ban.f(SourceFile:728)
    at net.minecraft.client.main.Main.main(SourceFile:148)

[/CODE]

Also WorldGuard doesn't allow any new mobs......... (ver 5.9) and WorldEdit too (5.6.2)... also banners/armor stands don't work in the version of carbon I'm using.

**Comment by Shevchik** [comment]
Provide version of carbon which you use

**Comment by ghost** [comment]
Using latest carbon.. Crashes don't happen on 1.7.2 MC, they seem to happen on all other 1.7 versions.

**Comment by Shevchik** [comment]
Latest is not a really valid answer.
Point to specific commit.

**Comment by NavidK0** [comment]
Too unspecific. Please submit a new issue with a list of your plugins, which version of carbon, and which version of spigot you are using.
