### ISSUE TITLE
Should be using ProtocolLib Maven repo

### ISSUE THREAD

**Issue by vemacs** [NavidK0/Carbon#38]
URL: http://repo.comphenix.net/content/groups/public
Version: com.comphenix.protocol:ProtocolLib-Spigot:3.6.0-SNAPSHOT

**Comment by vemacs** [comment]
It would also be cool if you guys could use org.spigotmc:spigot:1.7.10-R0.1-SNAPSHOT for the Spigot depends to aid in compilation

**Comment by NavidK0** [comment]
Fixed
