### ISSUE TITLE
[Bug] Sheep that die with fire aspect enchantment do not drop cooked mutton.

### ISSUE THREAD

**Issue by mibby** [NavidK0/Carbon#4]
https://github.com/NavidK0/Carbon/commit/b6d74c3418a4ae38674ae2cb52b04d46935a0361

**Comment by Shevchik** [comment]
Try on vanilla, if it drops cooked mutton when killed by fire aspect sword too, i will add that.

**Comment by mibby** [comment]
Tested on Vanilla singleplayer. Sheep do drop cooked mutton when killed with a fire aspect 2 diamond sword. Thus, should be fixed in Carbon.

**Comment by Shevchik** [comment]
Not realy easy to fix that, but i will try.

**Comment by pupnewfster** [comment]
Submitted a pull request that fixes this later will look into testing on vanilla what is interaction with looting enchantment to see if dropped amount needs to be changed if killed with looting.

**Comment by Shevchik** [comment]
Thanks.
Merged.
