### ISSUE TITLE
Diorite, Granite and Andesite generation.

### ISSUE THREAD

**Issue by SequaciousGAMES** [NavidK0/Carbon#43]
It seems that Diorite, Granite and Andesite don't spawn above ground in extreme hills like they're supposed to. In fact, in vanilla they spawn above ground in a few biomes. And as of Carbon 1.6.1 they still spawn less frequently than they should.

**Comment by NavidK0** [comment]
This is because of an error in the code in the block populator
It was checking for all blocks under 128, the old  height limit

**Comment by SequaciousGAMES** [comment]
Is it possible to fix?

**Comment by NavidK0** [comment]
Yes, I just fixed it.
