### ISSUE TITLE
[Feature request] Option to use ladders, air, or glass for barrier blocks on 1.7

### ISSUE THREAD

**Issue by vemacs** [NavidK0/Carbon#45]
None of these will work perfectly in all situations, but it would be nice to have the option.
- Ladders (possibly sideways) provide invisible barriers in 1.7, but won't work near walls.
- Air, well, it doesn't smoothly provide barriers, but some may prefer it over glass (aesthetics)
- Glass, what it is currently

In addition:
- Checkerboarded bottom half of iron doors, could possibly be computationally intensive to do (effectively replace only odd, odd coords and even, even coords for xy or yz, both work), but would work pretty well. Could be made even better by setting orientation based on neighboring blocks (iffy corners, but that's a small price to pay, and the server would knock back anyways).

**Comment by NavidK0** [comment]
I wouldn't do air, since that is what normally happens when 1.7.10 clients see 1.8 blocks without protocollib.

Ladders are an interesting idea.

**Comment by Wombosvideo** [comment]
I would also go with iron door parts (Invisible but not accessible)
They're like ladders, but completely invisible

**Comment by vemacs** [comment]
@NavidK0 I actually would put air as an option, as glass is not aesthetically pleasing in some scenarios, and in my scenario, that's actually preferred (even with the "forcefield" effect). Without ProtocolLib, there would no support for translating blocks AFAIK.

@Wombosvideo it's mentioned in the comments.

**Comment by Wombosvideo** [comment]
Oh, didn't see it ;-)

**Comment by NavidK0** [comment]
All blocks, items, and entities now have config options.
