### ISSUE TITLE
Instead of hacking/injecting the worldgen into the default MC worldgen, add it as a bukkit worldgen

### ISSUE THREAD

**Issue by ArtificialTruth** [NavidK0/Carbon#46]
I heard that you were considering creating a full 1.8 generator but wanted to inject it into the default Minecraft generator.
That will cause multiple problems:
1. If you don't want a world to have any 1.8 features in a world.
2. If you're using custom generators like PlotMe, SkyBlock, SkyGrid, Emptyworldgenerator etc.
3. You can no long prevent it from generating since you removed the whitelist.

There are 2 easy solutions to this problem, 2 is the best imo:
1. Add a list that can be toggled to whitelist or blacklist were you can define which worlds it should/shouldn't use
2. Add a generator called Carbon which can be added to either bukkit.yml or your preferred world handling system (ex. MultiVerse)

Forcing all worlds to have a full 1.8 generator is a bad idea.
As always, keep up the good work!

**Comment by StefenSharkey** [comment]
I agree with everything stated here, as well.

I understand making a custom world generator isn't exactly an easy thing to get perfect, but allowing users to enable and disable block (and upcoming terrain) generation in some way would be beneficial to all.

**Comment by NavidK0** [comment]
Reimplemented.
