### ISSUE TITLE
Pressure plates

### ISSUE THREAD

**Issue by externo6** [NavidK0/Carbon#47]
Hey, using Carbon 1.6.1, we have some plugins that interact with pressure plates, when using carbon they do not function. One is buttonwarps, the other is custom to us.

Thanks :)

**Comment by Wombosvideo** [comment]
What doesn't work? Like... which functions?

**Comment by externo6** [comment]
Plugins that listen on PlayerInteractEvent for pressureplates

**Comment by Wombosvideo** [comment]
Action.PHYSICAL.... yeah.. It's also blocked for me

**Comment by NavidK0** [comment]
That's odd... they should function like normal. Carbon reinjects all modified blocks back into the server, so they function like they normally would.

**Comment by externo6** [comment]
It works with Carbon 1.5, but not the 1.6 release.

**Comment by Wombosvideo** [comment]
same here

**Comment by Shevchik** [comment]
Should be fixed in latest dev build
