### ISSUE TITLE
Double red sandstone slabs issues

### ISSUE THREAD

**Issue by redsoxfan95** [NavidK0/Carbon#50]
If you spawn in a double red sandstone slab it crashes your client and you are unable to log in unless your inventory is cleared. When you spawn in water/lava blocks, it automatically replaces those with buckets of water/lava. Would it be possible to replace double red sandstone slabs with single ones?

Another red sandstone slab issue is when you place the second slab on top of the first one, it doesn't make a sound.

**Comment by Wombosvideo** [comment]
Since Lava and Water Blocks are removed in the 1.8 (as I heard), I think it's impossible to get arround that Lava Bucket Thingees. The single slab to doubleslab should be easy to fix since spigot allows you to play sounds on your own

**Comment by NavidK0** [comment]
Resolved.
