### ISSUE TITLE
1.6 Barrier Lighting Bug

### ISSUE THREAD

**Issue by TheMasterBlaster** [NavidK0/Carbon#56]
The lighting with Barriers is still bugged using Carbon. It seems Barriers do not allow light to pass through them. I find making a 4x4x4 box of Barriers allows you to see the error in the Lighting, As long as your not close to the Barriers when you reload. I'm not sure if this is even fixable but I hope it is.

**Comment by Wombosvideo** [comment]
Since you can send Light-Update packets to a player, it should be easy to fix
