### ISSUE TITLE
[Bug] Pressure plate recipes are wrong.

### ISSUE THREAD

**Issue by mibby** [NavidK0/Carbon#58]
Compiled as of source https://github.com/NavidK0/Carbon/commit/1a405f729a2b4478d965233537ace4cb4bb51de2

Recipe for weighted pressure plates are wrong. Gold ingots give you the heavy pressure plates and iron ingots give you the light ones
http://minecraft.gamepedia.com/Weighted_Pressure_Plate

**Comment by Wombosvideo** [comment]
That's a funny/strange bug, lol ;-)
