### ISSUE TITLE
[BUG] Only default rabbits spawn

### ISSUE THREAD

**Issue by pupnewfster** [NavidK0/Carbon#66]
Other variations of rabbits do not spawn naturally as well as they should spawn as 1 adult and 2 babies not as 3 adults as in vanilla.

**Comment by unicxa** [comment]
in sudo try to do a: Math.random() % skintypes.length; then return the skin type as a int and put in the injectRabbitSpawner()

**Comment by pupnewfster** [comment]
the calculating skin type isn't as much of an issue as that I am unsure where to specify skin types for the natural ones, as there is no actual entity yet as they have not spawnws.

**Comment by unicxa** [comment]
Also put another Random.nextboolean() for the spawning of a baby entity I.e babby rabbits. I'm sorry if I rushed I'm going to my campus atm

**Comment by pupnewfster** [comment]
It's fine can figure out more later when you have time or something.

**Comment by NavidK0** [comment]
I've fixed this. Kind of... there's no way to really determine if entities have spawned together in a group, so I simply check for entity spawns.
