### ISSUE TITLE
Banners do not "pop off" when blocks go missing

### ISSUE THREAD

**Issue by Puremin0rez** [NavidK0/Carbon#68]
If you hang a banner on a wall, then break the blocks supporting the banner, the banner continues to float.

This is not Vanilla behavior (but somewhat neat?).

**Comment by Shevchik** [comment]
Yea, thats because we don't override block physics yet.

**Comment by Wombosvideo** [comment]
You could also check for the block near the broken block and check if it's a banner. Should be relatively easy to fix but then it would also need to drop the item with nbt data

**Comment by NavidK0** [comment]
Banners don't drop the correct item either, it always drops black, that also needs to be fixed.

**Comment by Puremin0rez** [comment]
It always gives black when middle clicking them as well as spawning the pattern banners via command blocks.
