### ISSUE TITLE
[Feature Request] Have /Carbon show the Build Number

### ISSUE THREAD

**Issue by SequaciousGAMES** [NavidK0/Carbon#70]
Yeah this is a small one but the title basically says it all. It would be very useful if /carbon showed the build number as well as all the information it already does.

There's also an issue when I use new builds in which a new config (or new options aren't added to the config) until I delete the previous one.

**Comment by Wombosvideo** [comment]
<< 1st Part:
 Good Idea, already thought about this too. I'm gonna code this shortly...

**Comment by unicxa** [comment]
also Wom can you add the contributors to the /carbon command
My offical name i go by is sickray34s

**Comment by Wombosvideo** [comment]
of course, @unicxa

**Comment by Wombosvideo** [comment]
Does #71 add both of your requests? Or did I misunderstand something?

##Edit: I just saw that @InfinityAspire maybe meant the Jenkins Build number. It should be almost impossible to automaticly get this autoupdated. It should've been done every time you change something and upload it to jenkins... kinda  annoying

**Comment by Jikoo** [comment]
@Wombosvideo It can be done in the build script, but I don't remember how.

**Comment by NavidK0** [comment]
Not possible to show the Jenkins build number without somehow connecting to the website.
Version number has been added.
