### ISSUE TITLE
[Feature suport/ bug] Chests from 1.8 worlds

### ISSUE THREAD

**Issue by ghost** [NavidK0/Carbon#76]
So i have the latest version of spigot with the latest patch and i have the latest carbon version. I have a server that ran the vanila server file and generated a world. When i transfer the world save file to the spigot server with carbon on it. all the continence of the chests is deleted. if this is a bug can you fix it and if its a spigot isue could you add a feature that stops the deletion. thanks

**Comment by Wombosvideo** [comment]
I think it's impossible to fix, cause it's not an actual 1.8 Server and maybe an injected version of the 1.8 generator could lead to main bugs

**Comment by TheMasterBlaster** [comment]
Its a thing with Minecraft itself. 1.8 worlds lose some data when loaded using 1.7 servers. and as far as I know that is impossible to fix using a plugin.

**Comment by NavidK0** [comment]
Not possible to fix this, the server remains at 1.7.10, normally downgrading maps from a newer server causes problems anyways.
