### ISSUE TITLE
[Bug] New enchanting system is very cheaty

### ISSUE THREAD

**Issue by Puremin0rez** [NavidK0/Carbon#78]
The new 1.8 enchantment system requires lower levels, however, the enchants should always stay the same until an enchantment is picked. Each player on the server has a "unique id" used for enchanting.

The current system lacks this unique hash, and reinserting the item over and over again reveals a new enchant every time. This effectively makes enchanting useless and OP.

Until this is fixed I recommend making the new enchantment system be configurable.

**Comment by Puremin0rez** [comment]
Refer to
http://minecraft.gamepedia.com/Enchanting

for more information.

**Comment by Shevchik** [comment]
THe problem is that the random seed is stored entity nbt, and i can't store it there too, because it will be overwritten :(.
Don't have an idea whre should i store it.

**Comment by Puremin0rez** [comment]
I suppose you could store it in memory, so the seed would only be lost when the server rebooted - that way it can't really be "abused" as much.

**Comment by Shevchik** [comment]
I found a way to store it in entity nbt data. Will add it soon.

**Comment by Wombosvideo** [comment]
YAY! Finally. @Shevchik

**Comment by Shevchik** [comment]
Should be fixed now
