### ISSUE TITLE
[bug?] new Doors

### ISSUE THREAD

**Issue by RawrUniversal** [NavidK0/Carbon#8]
If you click the top half of the door, it opens, but you cant walk through it. It shows its open, but it really isnt.
(door locked with LWC)

**Comment by Shevchik** [comment]
Can open and walk through just fine.
Probably an ncp issue, should check this.

**Comment by NavidK0** [comment]
Server crashes when opening top half of door.

EDIT: Nevermind, it only happened once.

I'm on a server without NCP, no issues with doors here.
