### ISSUE TITLE
Charged Creeper Mob Head Drop

### ISSUE THREAD

**Issue by TheMasterBlaster** [NavidK0/Carbon#82]
When a Charged Creeper explodes and kills mobs only one head should drop in total. As of the Latest Carbon build it seems every mob that dies by the Charged Creeper drops their head.

**Comment by NavidK0** [comment]
I'm not quite sure how to solve this one. Currently, Bukkit is used to spawn the mob heads, but there's no elegant solution to get all the mobs affected by a single creeper.

**Comment by Wombosvideo** [comment]
Get the radius of the creeper explosion and then the entities in the range of the creeper

**Comment by NavidK0** [comment]
I was hoping for a less hacky method, because if you check an entity death event, then all of the entities around the creeper may not have actually died, and if you check on an entity explode event, you can't check their health as soon as the entity explodes.

**Comment by Shevchik** [comment]
I have an idea how to fix that.

**Comment by Jikoo** [comment]
Only idea I've come up with is as follows:
When a charged creeper dies, its UUID could be added to a set. A task on a delay of a couple ticks would be started to remove it.
When a mob dies to a charged creeper, the set is checked. If it contains the creeper's UUID, the UUID is removed from the set and a head is dropped. If not, no head.

**Comment by Wombosvideo** [comment]
Good Idea @Jikoo

**Comment by Jikoo** [comment]
After testing, my original idea is unreliable - No EntityDeathEvent appears to be fired when a creeper actually explodes, and no EntityExplodeEvent is fired if gamerule mobGriefing is false. I've got another idea that should be workable, so I'll try that instead.
