### ISSUE TITLE
[Bug] Lapis Lazuli is pre spawned in Enchantment Tables

### ISSUE THREAD

**Issue by Puremin0rez** [NavidK0/Carbon#86]
The Spigot Protocol Patch automatically puts a "fake" lapis lazuli in the enchantment table to keep the enchantment table working fine for 1.8 clients.

Obviously this isn't a vanilla feature and players should be required to get lapis to enchant things.

Not quite sure how'd you override spigot doing that.

**Comment by aianmoo16** [comment]
Not a bug... its a spigot thing

**Comment by Puremin0rez** [comment]
Did you even read my issue? I know it's a Spigot thing. I'm hoping Carbon can workaround it.

Spigot won't "fix it" because it's a protocol build meant for compatibility, not 1.8 features.

**Comment by aianmoo16** [comment]
lol I misread things alot

**Comment by unicxa** [comment]
Possible but I think it will be a little hard

**Comment by aianmoo16** [comment]
exactly ^

**Comment by Puremin0rez** [comment]
@Shevchik You do some fantastic work, thank you.
