### ISSUE TITLE
Enchantment Bug[Latest Dev Build #44 ]

### ISSUE THREAD

**Issue by rocky143** [NavidK0/Carbon#88]
Latest dev build fix some good issue which made me wanting to try but now there is an issue with forced me to downgrade. 
Dev build #44 added an issue of being charged way less xp for using Enchanting Tables.
If trying to enchant a level 30, when clicked on it, it will only charge you 3 xp and it is happening to other lower levels as well like 10 would charge 1 upon clicking on it.
Downgraded to the stable build, the stable build however contain a bug where it makes it impossible to use the Anvil for enchantment multiplying. Once clicked on the wanted item in an anvil, you will be charged xp but the item you suppose to get will not be given but the 2 ingredients will be given back.

**Comment by Shevchik** [comment]
That is not a bug, read how new mechanics work.
