### ISSUE TITLE
[Invalid] Mobs do not respect fence property of new 1.8 fences.

### ISSUE THREAD

**Issue by mibby** [NavidK0/Carbon#9]
Compiled source as of commit
https://github.com/NavidK0/Carbon/commit/0e41b8521138f35982cb5c952e3b821e874193d7

Spigot with patch 20140927a.

~~Mobs do not respect the fence property of the new 1.8 fences. They phase/walk through the fence block.~~

**Comment by Shevchik** [comment]
Strange, it works for me.

**Comment by mibby** [comment]
Odd. I'll re-test. Created the ticket as I had a report from a player that mobs were going through the new fences.

**Comment by mibby** [comment]
Seems to be working. I'll mark as invalid. Apologies for the ticket, will confirm player in-game reports before creating new tickets.
