### ISSUE TITLE
Two doors are dropping when breaking a door.

### ISSUE THREAD

**Issue by mibby** [NavidK0/Carbon#92]
Compiled as of commit https://github.com/NavidK0/Carbon/commit/f8a96041041590010ce4d2039069cd31e65379cc

When breaking one of the new 1.8 doors in survival, two doors drop instead of one.

**Comment by Curtis3321** [comment]
Also would like to note when in creative it drops a door too.

**Comment by rlf** [comment]
Also, piggy backing another defect, doors don't stack to more than 3.

**Comment by NavidK0** [comment]
Fixed with commit:
https://github.com/NavidK0/Carbon/commit/eeeae0adadaf3303c097b256c2f0181a9a86a326

**Comment by mibby** [comment]
@NavidK0 Compiled as of commit https://github.com/NavidK0/Carbon/commit/755213a8891bb2352aa3368939c9f65b83f5f040

New doors still drop 2 doors when breaking in survival, breaking the bottom half. Reopen ticket please.

**Comment by NavidK0** [comment]
Ah
I see the issue now.

**Comment by NavidK0** [comment]
Indirect door break and door break are both spawning items, and the indirect door hasn't been updated.

**Comment by NavidK0** [comment]
Fixed with commit:
https://github.com/NavidK0/Carbon/commit/682c2bacc067c420f697169e250426d30ae9aef4
