### ISSUE TITLE
[Bug] Bad Packet ID 71

### ISSUE THREAD

**Issue by Puremin0rez** [NavidK0/Carbon#93]
Occurs when trying to login with MC 1.7.10 on a server with the latest Carbon (built from: https://github.com/NavidK0/Carbon/commit/2365f2c0b655214996fbce029341e60826a0f396)

ProtocolLib is enabled.

**Comment by Shevchik** [comment]
Can't reproduce. 
Do you have an error log of some sort?
Also packet 71 is player list head/footer packet, it doesn't exist in 1.7, but we don't send it.

**Comment by Wombosvideo** [comment]
It's because @Puremin0rez  has a Plugin installed changing the Header and Footer of the Tab-List....
The old behaviour doesn't work in the 1.7.10 Versions.... So.. If you use ProtocolInjector make sure your users are on 1.8

**Comment by Puremin0rez** [comment]
@Wombosvideo Ah! That's exactly it. Thank you :)
