### ISSUE TITLE
Banners don't show patterns (data) on them in inventory

### ISSUE THREAD

**Issue by Puremin0rez** [NavidK0/Carbon#94]
Related to https://github.com/NavidK0/Carbon/issues/75

Banners don't appear to show the pattern data when crafted or spawned in - in the case of crafting, you will see the pattern for a split second before showing the default blue banner.

However placing the banner will still reveal the pattern in world.

http://i.imgur.com/rikpKnT.png

**Comment by Shevchik** [comment]
Bukkit/Spigot removes nbt data of unknown items on send. I can override this, but that will be really hard.

**Comment by Wombosvideo** [comment]
@Shevchik If you'd get this working, do you allow me using it in my own (upcomming RPG) Plugin?

**Comment by Shevchik** [comment]
Should now work

**Comment by Puremin0rez** [comment]
They do now work, however, if you have it in your inventory and you open the creative inventory it'll instantly wipe the data from the banner. So basically it works fine in Survival Mode.

**Comment by Shevchik** [comment]
Bukkit/Spigot has incoming scrambler too, should fix that.

**Comment by Shevchik** [comment]
Well, looks like it didn't work properly, now you can craft them just fine, but as soon as i put them in inventory something clears nbt :(

**Comment by Puremin0rez** [comment]
Haha, one step at a time I suppose. Not sure if I'm doing something wrong but it seems as if command block spawned banners are all returning black now? Can't seem to get patterns to work. Can anyone confirm?

**Comment by Jikoo** [comment]
Command blocks are working fine for me with /give and /setblock, do you have an aggressive NBT cleaning plugin? Mine only cleans items when they're spawned from creative, not picked up or clicked in inventory.

**Comment by HunTwig** [comment]
So there is no fix? Survival or Not I can't add patterns to banners. :-/

**Comment by Shevchik** [comment]
I can, but i will have to override all containers for this :(.

**Comment by HunTwig** [comment]
What do you mean?

**Comment by unicxa** [comment]
He will have to basically "store" all the patterns in a list/map and "override" all of the inventorys / chest for this to work at least. that's what I assume.

**Comment by unicxa** [comment]
thats pretty hard knowing my experience storeing data in a map/list

**Comment by unicxa** [comment]
and getting all inventorys aswell

**Comment by unicxa** [comment]
in this they are using NTB tags that open a File that stores data on it and is able to be called by name in a method

**Comment by Shevchik** [comment]
Something like that. I will have to store patterns in attributes tag list, so bukkit won't wipe them. I can account them in recipe, and while sending data to player, so nobody will notice. But that won't transfer to vanilla at all. I opened a feature request at spigot for adding custom craftitemmeta api, but if they won't do anything - i will have to implement this method.

**Comment by Shevchik** [comment]
Banners now use lore internally(server side). Lore is remapped to nbt when sending to client or placing the banners. NBT is recoded to lore when receiving data form client or breaking banner, so players won't notice this. But due to this item banners no longer support nbt and also item banners will lose patterns when transferred to vanilla.

**Comment by Puremin0rez** [comment]
For clarifications, only banners that are items will lose patterns when loaded in vanilla - not in world banners, correct?

**Comment by Shevchik** [comment]
Yes

**Comment by Puremin0rez** [comment]
Well, just had a test and everything looks good on my end. If you're comfortable with how they work now, you're welcome to close this issue :)
